# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:/bsw_programation/01_maya/Pipeline/bsPipe/bsPipe/bs_ui/bsui_texture/bsui_textureManager.ui'
#
# Created: Fri Sep 01 14:29:15 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_bstm_mainWindow_MW(object):
    def setupUi(self, bstm_mainWindow_MW):
        bstm_mainWindow_MW.setObjectName("bstm_mainWindow_MW")
        bstm_mainWindow_MW.resize(754, 368)
        self.centralwidget = QtGui.QWidget(bstm_mainWindow_MW)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bstm_logo_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bstm_logo_lbl.sizePolicy().hasHeightForWidth())
        self.bstm_logo_lbl.setSizePolicy(sizePolicy)
        self.bstm_logo_lbl.setMaximumSize(QtCore.QSize(600, 50))
        self.bstm_logo_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bstm_logo_lbl.setObjectName("bstm_logo_lbl")
        self.verticalLayout_5.addWidget(self.bstm_logo_lbl)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.bstm_assetType_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bstm_assetType_lbl.sizePolicy().hasHeightForWidth())
        self.bstm_assetType_lbl.setSizePolicy(sizePolicy)
        self.bstm_assetType_lbl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.bstm_assetType_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bstm_assetType_lbl.setObjectName("bstm_assetType_lbl")
        self.gridLayout.addWidget(self.bstm_assetType_lbl, 1, 0, 1, 1)
        self.bstm_assetName_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bstm_assetName_lbl.sizePolicy().hasHeightForWidth())
        self.bstm_assetName_lbl.setSizePolicy(sizePolicy)
        self.bstm_assetName_lbl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.bstm_assetName_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bstm_assetName_lbl.setObjectName("bstm_assetName_lbl")
        self.gridLayout.addWidget(self.bstm_assetName_lbl, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(116, 0))
        self.label_9.setMaximumSize(QtCore.QSize(116, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.bstm_currentRootPath_le = QtGui.QLineEdit(self.centralwidget)
        self.bstm_currentRootPath_le.setObjectName("bstm_currentRootPath_le")
        self.horizontalLayout_2.addWidget(self.bstm_currentRootPath_le)
        self.bstm_currentRootPath_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bstm_currentRootPath_pb.sizePolicy().hasHeightForWidth())
        self.bstm_currentRootPath_pb.setSizePolicy(sizePolicy)
        self.bstm_currentRootPath_pb.setMaximumSize(QtCore.QSize(25, 16777215))
        self.bstm_currentRootPath_pb.setObjectName("bstm_currentRootPath_pb")
        self.horizontalLayout_2.addWidget(self.bstm_currentRootPath_pb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(116, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.bstm_convertPath_le = QtGui.QLineEdit(self.centralwidget)
        self.bstm_convertPath_le.setObjectName("bstm_convertPath_le")
        self.horizontalLayout_3.addWidget(self.bstm_convertPath_le)
        self.bstm_convertPath_pb = QtGui.QPushButton(self.centralwidget)
        self.bstm_convertPath_pb.setObjectName("bstm_convertPath_pb")
        self.horizontalLayout_3.addWidget(self.bstm_convertPath_pb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_6.addWidget(self.line_5)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.bstm_exportShader_pb = QtGui.QPushButton(self.centralwidget)
        self.bstm_exportShader_pb.setObjectName("bstm_exportShader_pb")
        self.verticalLayout.addWidget(self.bstm_exportShader_pb)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.bstm_exportPath_le = QtGui.QLineEdit(self.centralwidget)
        self.bstm_exportPath_le.setObjectName("bstm_exportPath_le")
        self.horizontalLayout_4.addWidget(self.bstm_exportPath_le)
        self.bstm_exportedPath_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bstm_exportedPath_pb.sizePolicy().hasHeightForWidth())
        self.bstm_exportedPath_pb.setSizePolicy(sizePolicy)
        self.bstm_exportedPath_pb.setMaximumSize(QtCore.QSize(25, 16777215))
        self.bstm_exportedPath_pb.setObjectName("bstm_exportedPath_pb")
        self.horizontalLayout_4.addWidget(self.bstm_exportedPath_pb)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.bstm_importShader_pb = QtGui.QPushButton(self.centralwidget)
        self.bstm_importShader_pb.setObjectName("bstm_importShader_pb")
        self.verticalLayout_2.addWidget(self.bstm_importShader_pb)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.bstm_refresh_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bstm_refresh_pb.sizePolicy().hasHeightForWidth())
        self.bstm_refresh_pb.setSizePolicy(sizePolicy)
        self.bstm_refresh_pb.setObjectName("bstm_refresh_pb")
        self.verticalLayout_6.addWidget(self.bstm_refresh_pb)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 2, 0, 1, 1)
        bstm_mainWindow_MW.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(bstm_mainWindow_MW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        bstm_mainWindow_MW.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(bstm_mainWindow_MW)
        self.statusBar.setObjectName("statusBar")
        bstm_mainWindow_MW.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(bstm_mainWindow_MW)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(bstm_mainWindow_MW)
        QtCore.QMetaObject.connectSlotsByName(bstm_mainWindow_MW)

    def retranslateUi(self, bstm_mainWindow_MW):
        bstm_mainWindow_MW.setWindowTitle(QtGui.QApplication.translate("bstm_mainWindow_MW", "BSW Texture Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.bstm_logo_lbl.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "BSW LOGO", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "Asset Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "Asset Name", None, QtGui.QApplication.UnicodeUTF8))
        self.bstm_assetType_lbl.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.bstm_assetName_lbl.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "File Texture Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "Current Root Path:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bstm_currentRootPath_pb.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "Convert Path Into Env:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bstm_convertPath_pb.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "convert Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "Shaders", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "Export All Shaders", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "Note:- Default Shader not be exported", None, QtGui.QApplication.UnicodeUTF8))
        self.bstm_exportShader_pb.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "Export Shaders", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "Exported Shader Path:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bstm_exportedPath_pb.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "Import Shaders on current File", None, QtGui.QApplication.UnicodeUTF8))
        self.bstm_importShader_pb.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "Import Shaders", None, QtGui.QApplication.UnicodeUTF8))
        self.bstm_refresh_pb.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("bstm_mainWindow_MW", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("bstm_mainWindow_MW", "Exit", None, QtGui.QApplication.UnicodeUTF8))

