# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:/bsw_programation/01_maya/Pipeline/bsPipe/bsPipe/bs_ui/bsui_anim/bsui_shotBrowser.ui'
#
# Created: Wed Nov 01 16:17:28 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_bsbr_ShotBrowser_MW(object):
    def setupUi(self, bsbr_ShotBrowser_MW):
        bsbr_ShotBrowser_MW.setObjectName("bsbr_ShotBrowser_MW")
        bsbr_ShotBrowser_MW.resize(858, 657)
        self.centralwidget = QtGui.QWidget(bsbr_ShotBrowser_MW)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bsbr_open_PB = QtGui.QPushButton(self.centralwidget)
        self.bsbr_open_PB.setMinimumSize(QtCore.QSize(100, 40))
        self.bsbr_open_PB.setStyleSheet("")
        self.bsbr_open_PB.setObjectName("bsbr_open_PB")
        self.horizontalLayout.addWidget(self.bsbr_open_PB)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bsbr_import_PB = QtGui.QPushButton(self.centralwidget)
        self.bsbr_import_PB.setMinimumSize(QtCore.QSize(100, 40))
        self.bsbr_import_PB.setStyleSheet("")
        self.bsbr_import_PB.setObjectName("bsbr_import_PB")
        self.horizontalLayout.addWidget(self.bsbr_import_PB)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.horizontalLayout, 7, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bsbr_shotVersion_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_shotVersion_lbl.setMinimumSize(QtCore.QSize(0, 24))
        self.bsbr_shotVersion_lbl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.bsbr_shotVersion_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsbr_shotVersion_lbl.setObjectName("bsbr_shotVersion_lbl")
        self.gridLayout_3.addWidget(self.bsbr_shotVersion_lbl, 0, 0, 1, 1)
        self.bsbr_shotDetails_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_shotDetails_lbl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.bsbr_shotDetails_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsbr_shotDetails_lbl.setObjectName("bsbr_shotDetails_lbl")
        self.gridLayout_3.addWidget(self.bsbr_shotDetails_lbl, 0, 1, 1, 1)
        self.bsbr_shotVersion_LW = QtGui.QListWidget(self.centralwidget)
        self.bsbr_shotVersion_LW.setMaximumSize(QtCore.QSize(16777215, 200))
        self.bsbr_shotVersion_LW.setObjectName("bsbr_shotVersion_LW")
        self.gridLayout_3.addWidget(self.bsbr_shotVersion_LW, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bsbr_fileNameTag_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_fileNameTag_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bsbr_fileNameTag_lbl.setObjectName("bsbr_fileNameTag_lbl")
        self.gridLayout_2.addWidget(self.bsbr_fileNameTag_lbl, 0, 0, 1, 1)
        self.bsbr_fileName_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_fileName_lbl.setMinimumSize(QtCore.QSize(150, 0))
        self.bsbr_fileName_lbl.setObjectName("bsbr_fileName_lbl")
        self.gridLayout_2.addWidget(self.bsbr_fileName_lbl, 0, 1, 1, 1)
        self.bsbr_sizeTag_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_sizeTag_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bsbr_sizeTag_lbl.setObjectName("bsbr_sizeTag_lbl")
        self.gridLayout_2.addWidget(self.bsbr_sizeTag_lbl, 1, 0, 1, 1)
        self.bsbr_size_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_size_lbl.setObjectName("bsbr_size_lbl")
        self.gridLayout_2.addWidget(self.bsbr_size_lbl, 1, 1, 1, 1)
        self.bsbr_ownerTag_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_ownerTag_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bsbr_ownerTag_lbl.setObjectName("bsbr_ownerTag_lbl")
        self.gridLayout_2.addWidget(self.bsbr_ownerTag_lbl, 2, 0, 1, 1)
        self.bsbr_owner_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_owner_lbl.setObjectName("bsbr_owner_lbl")
        self.gridLayout_2.addWidget(self.bsbr_owner_lbl, 2, 1, 1, 1)
        self.bsbr_lastModifiedTag_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_lastModifiedTag_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bsbr_lastModifiedTag_lbl.setObjectName("bsbr_lastModifiedTag_lbl")
        self.gridLayout_2.addWidget(self.bsbr_lastModifiedTag_lbl, 3, 0, 1, 1)
        self.bsbr_lastModified_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_lastModified_lbl.setObjectName("bsbr_lastModified_lbl")
        self.gridLayout_2.addWidget(self.bsbr_lastModified_lbl, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 5, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bsbr_layout_RB = QtGui.QRadioButton(self.centralwidget)
        self.bsbr_layout_RB.setObjectName("bsbr_layout_RB")
        self.horizontalLayout_2.addWidget(self.bsbr_layout_RB)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.bsbr_animation_RB = QtGui.QRadioButton(self.centralwidget)
        self.bsbr_animation_RB.setObjectName("bsbr_animation_RB")
        self.horizontalLayout_2.addWidget(self.bsbr_animation_RB)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.bsbr_refresh_PB = QtGui.QPushButton(self.centralwidget)
        self.bsbr_refresh_PB.setMinimumSize(QtCore.QSize(0, 25))
        self.bsbr_refresh_PB.setObjectName("bsbr_refresh_PB")
        self.horizontalLayout_2.addWidget(self.bsbr_refresh_PB)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.bsbr_logo_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_logo_lbl.setMinimumSize(QtCore.QSize(775, 40))
        self.bsbr_logo_lbl.setMaximumSize(QtCore.QSize(840, 40))
        self.bsbr_logo_lbl.setObjectName("bsbr_logo_lbl")
        self.gridLayout_4.addWidget(self.bsbr_logo_lbl, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bsbr_episode_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_episode_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsbr_episode_lbl.setObjectName("bsbr_episode_lbl")
        self.gridLayout.addWidget(self.bsbr_episode_lbl, 0, 0, 1, 1)
        self.bsbr_sequence_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_sequence_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsbr_sequence_lbl.setObjectName("bsbr_sequence_lbl")
        self.gridLayout.addWidget(self.bsbr_sequence_lbl, 0, 1, 1, 1)
        self.bsbr_shot_lbl = QtGui.QLabel(self.centralwidget)
        self.bsbr_shot_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsbr_shot_lbl.setObjectName("bsbr_shot_lbl")
        self.gridLayout.addWidget(self.bsbr_shot_lbl, 0, 2, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bsbr_episodeSearch_LE = QtGui.QLineEdit(self.centralwidget)
        self.bsbr_episodeSearch_LE.setObjectName("bsbr_episodeSearch_LE")
        self.verticalLayout.addWidget(self.bsbr_episodeSearch_LE)
        self.bsbr_episode_LW = QtGui.QListWidget(self.centralwidget)
        self.bsbr_episode_LW.setMinimumSize(QtCore.QSize(0, 225))
        self.bsbr_episode_LW.setObjectName("bsbr_episode_LW")
        self.verticalLayout.addWidget(self.bsbr_episode_LW)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bsbr_sequenceSearch_LE = QtGui.QLineEdit(self.centralwidget)
        self.bsbr_sequenceSearch_LE.setObjectName("bsbr_sequenceSearch_LE")
        self.verticalLayout_2.addWidget(self.bsbr_sequenceSearch_LE)
        self.bsbr_sequence_LW = QtGui.QListWidget(self.centralwidget)
        self.bsbr_sequence_LW.setObjectName("bsbr_sequence_LW")
        self.verticalLayout_2.addWidget(self.bsbr_sequence_LW)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bsbr_shotSearch_LE = QtGui.QLineEdit(self.centralwidget)
        self.bsbr_shotSearch_LE.setObjectName("bsbr_shotSearch_LE")
        self.verticalLayout_3.addWidget(self.bsbr_shotSearch_LE)
        self.bsbr_shot_LW = QtGui.QListWidget(self.centralwidget)
        self.bsbr_shot_LW.setObjectName("bsbr_shot_LW")
        self.verticalLayout_3.addWidget(self.bsbr_shot_LW)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 4, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 3, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 6, 0, 1, 1)
        bsbr_ShotBrowser_MW.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(bsbr_ShotBrowser_MW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        bsbr_ShotBrowser_MW.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(bsbr_ShotBrowser_MW)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(bsbr_ShotBrowser_MW)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(bsbr_ShotBrowser_MW)
        QtCore.QMetaObject.connectSlotsByName(bsbr_ShotBrowser_MW)

    def retranslateUi(self, bsbr_ShotBrowser_MW):
        bsbr_ShotBrowser_MW.setWindowTitle(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Shot Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_open_PB.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_import_PB.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_shotVersion_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Shot Versions", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_shotDetails_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Shot Details", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_fileNameTag_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "File Name:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_fileName_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Not Exist", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_sizeTag_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Size:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_size_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Not Exist", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_ownerTag_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Owner:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_owner_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Not Exist", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_lastModifiedTag_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Last Modified:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_lastModified_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Not Exist", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_layout_RB.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_animation_RB.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_refresh_PB.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_logo_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Shot Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_episode_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Episode", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_sequence_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.bsbr_shot_lbl.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("bsbr_ShotBrowser_MW", "About", None, QtGui.QApplication.UnicodeUTF8))

