# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:/bsw_programation/01_maya/Pipeline/bsPipe/bsPipe/bs_ui/bsui_anim/bsui_shotBuilder.ui'
#
# Created: Thu Sep 21 18:08:27 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_bssb_shotBuilderMainWindow(object):
    def setupUi(self, bssb_shotBuilderMainWindow):
        bssb_shotBuilderMainWindow.setObjectName("bssb_shotBuilderMainWindow")
        bssb_shotBuilderMainWindow.resize(668, 714)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(bssb_shotBuilderMainWindow.sizePolicy().hasHeightForWidth())
        bssb_shotBuilderMainWindow.setSizePolicy(sizePolicy)
        bssb_shotBuilderMainWindow.setMinimumSize(QtCore.QSize(668, 714))
        bssb_shotBuilderMainWindow.setMaximumSize(QtCore.QSize(668, 716))
        self.centralwidget = QtGui.QWidget(bssb_shotBuilderMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.bssb_logo_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bssb_logo_lbl.sizePolicy().hasHeightForWidth())
        self.bssb_logo_lbl.setSizePolicy(sizePolicy)
        self.bssb_logo_lbl.setMinimumSize(QtCore.QSize(650, 40))
        self.bssb_logo_lbl.setMaximumSize(QtCore.QSize(700, 40))
        self.bssb_logo_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bssb_logo_lbl.setObjectName("bssb_logo_lbl")
        self.gridLayout.addWidget(self.bssb_logo_lbl, 0, 0, 1, 3)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtGui.QSpacerItem(50, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bssb_episode_lbl = QtGui.QLabel(self.centralwidget)
        self.bssb_episode_lbl.setObjectName("bssb_episode_lbl")
        self.horizontalLayout_6.addWidget(self.bssb_episode_lbl)
        self.bssb_episode_LE = QtGui.QLineEdit(self.centralwidget)
        self.bssb_episode_LE.setObjectName("bssb_episode_LE")
        self.horizontalLayout_6.addWidget(self.bssb_episode_LE)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.bssb_sequence_lbl = QtGui.QLabel(self.centralwidget)
        self.bssb_sequence_lbl.setObjectName("bssb_sequence_lbl")
        self.horizontalLayout_6.addWidget(self.bssb_sequence_lbl)
        self.bssb_sequence_LE = QtGui.QLineEdit(self.centralwidget)
        self.bssb_sequence_LE.setObjectName("bssb_sequence_LE")
        self.horizontalLayout_6.addWidget(self.bssb_sequence_LE)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.bssb_shot_lbl = QtGui.QLabel(self.centralwidget)
        self.bssb_shot_lbl.setObjectName("bssb_shot_lbl")
        self.horizontalLayout_6.addWidget(self.bssb_shot_lbl)
        self.bssb_shot_LE = QtGui.QLineEdit(self.centralwidget)
        self.bssb_shot_LE.setObjectName("bssb_shot_LE")
        self.horizontalLayout_6.addWidget(self.bssb_shot_LE)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtGui.QSpacerItem(50, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bssb_startFrame_lbl = QtGui.QLabel(self.centralwidget)
        self.bssb_startFrame_lbl.setObjectName("bssb_startFrame_lbl")
        self.horizontalLayout_5.addWidget(self.bssb_startFrame_lbl)
        self.bssb_startFrame_spinBox = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bssb_startFrame_spinBox.sizePolicy().hasHeightForWidth())
        self.bssb_startFrame_spinBox.setSizePolicy(sizePolicy)
        self.bssb_startFrame_spinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.bssb_startFrame_spinBox.setMaximum(1000)
        self.bssb_startFrame_spinBox.setObjectName("bssb_startFrame_spinBox")
        self.horizontalLayout_5.addWidget(self.bssb_startFrame_spinBox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.bssb_endFrame_lbl = QtGui.QLabel(self.centralwidget)
        self.bssb_endFrame_lbl.setObjectName("bssb_endFrame_lbl")
        self.horizontalLayout_5.addWidget(self.bssb_endFrame_lbl)
        self.bssb_endFrame_spinBox = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bssb_endFrame_spinBox.sizePolicy().hasHeightForWidth())
        self.bssb_endFrame_spinBox.setSizePolicy(sizePolicy)
        self.bssb_endFrame_spinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.bssb_endFrame_spinBox.setMaximum(1000)
        self.bssb_endFrame_spinBox.setObjectName("bssb_endFrame_spinBox")
        self.horizontalLayout_5.addWidget(self.bssb_endFrame_spinBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_7, 1, 0, 1, 3)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bssb_riggedAsset_lbl = QtGui.QLabel(self.centralwidget)
        self.bssb_riggedAsset_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bssb_riggedAsset_lbl.setObjectName("bssb_riggedAsset_lbl")
        self.verticalLayout_5.addWidget(self.bssb_riggedAsset_lbl)
        self.bssb_assets_tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bssb_assets_tabWidget.sizePolicy().hasHeightForWidth())
        self.bssb_assets_tabWidget.setSizePolicy(sizePolicy)
        self.bssb_assets_tabWidget.setMinimumSize(QtCore.QSize(301, 441))
        self.bssb_assets_tabWidget.setMaximumSize(QtCore.QSize(301, 441))
        self.bssb_assets_tabWidget.setObjectName("bssb_assets_tabWidget")
        self.Chars_tab = QtGui.QWidget()
        self.Chars_tab.setObjectName("Chars_tab")
        self.layoutWidget = QtGui.QWidget(self.Chars_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 291, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bssb_charSearch_lbl = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bssb_charSearch_lbl.sizePolicy().hasHeightForWidth())
        self.bssb_charSearch_lbl.setSizePolicy(sizePolicy)
        self.bssb_charSearch_lbl.setMinimumSize(QtCore.QSize(20, 20))
        self.bssb_charSearch_lbl.setMaximumSize(QtCore.QSize(20, 20))
        self.bssb_charSearch_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bssb_charSearch_lbl.setObjectName("bssb_charSearch_lbl")
        self.horizontalLayout_4.addWidget(self.bssb_charSearch_lbl)
        self.bssb_charSearch_LE = QtGui.QLineEdit(self.layoutWidget)
        self.bssb_charSearch_LE.setObjectName("bssb_charSearch_LE")
        self.horizontalLayout_4.addWidget(self.bssb_charSearch_LE)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.bssb_chars_LW = QtGui.QListWidget(self.layoutWidget)
        self.bssb_chars_LW.setObjectName("bssb_chars_LW")
        self.verticalLayout.addWidget(self.bssb_chars_LW)
        self.bssb_assets_tabWidget.addTab(self.Chars_tab, "")
        self.Props_tab = QtGui.QWidget()
        self.Props_tab.setObjectName("Props_tab")
        self.layoutWidget1 = QtGui.QWidget(self.Props_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 291, 411))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bssb_propSearch_lbl = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bssb_propSearch_lbl.sizePolicy().hasHeightForWidth())
        self.bssb_propSearch_lbl.setSizePolicy(sizePolicy)
        self.bssb_propSearch_lbl.setMinimumSize(QtCore.QSize(20, 20))
        self.bssb_propSearch_lbl.setMaximumSize(QtCore.QSize(20, 20))
        self.bssb_propSearch_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bssb_propSearch_lbl.setObjectName("bssb_propSearch_lbl")
        self.horizontalLayout_3.addWidget(self.bssb_propSearch_lbl)
        self.bssb_propSearch_LE = QtGui.QLineEdit(self.layoutWidget1)
        self.bssb_propSearch_LE.setObjectName("bssb_propSearch_LE")
        self.horizontalLayout_3.addWidget(self.bssb_propSearch_LE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.bssb_props_LW = QtGui.QListWidget(self.layoutWidget1)
        self.bssb_props_LW.setObjectName("bssb_props_LW")
        self.verticalLayout_2.addWidget(self.bssb_props_LW)
        self.bssb_assets_tabWidget.addTab(self.Props_tab, "")
        self.Set_tab = QtGui.QWidget()
        self.Set_tab.setObjectName("Set_tab")
        self.layoutWidget2 = QtGui.QWidget(self.Set_tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 291, 411))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bssb_setSearch_lbl = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bssb_setSearch_lbl.sizePolicy().hasHeightForWidth())
        self.bssb_setSearch_lbl.setSizePolicy(sizePolicy)
        self.bssb_setSearch_lbl.setMinimumSize(QtCore.QSize(20, 20))
        self.bssb_setSearch_lbl.setMaximumSize(QtCore.QSize(20, 20))
        self.bssb_setSearch_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bssb_setSearch_lbl.setObjectName("bssb_setSearch_lbl")
        self.horizontalLayout_2.addWidget(self.bssb_setSearch_lbl)
        self.bssb_setSearch_LE = QtGui.QLineEdit(self.layoutWidget2)
        self.bssb_setSearch_LE.setObjectName("bssb_setSearch_LE")
        self.horizontalLayout_2.addWidget(self.bssb_setSearch_LE)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.bssb_set_LW = QtGui.QListWidget(self.layoutWidget2)
        self.bssb_set_LW.setObjectName("bssb_set_LW")
        self.verticalLayout_3.addWidget(self.bssb_set_LW)
        self.bssb_assets_tabWidget.addTab(self.Set_tab, "")
        self.Vehicles_tab = QtGui.QWidget()
        self.Vehicles_tab.setObjectName("Vehicles_tab")
        self.layoutWidget3 = QtGui.QWidget(self.Vehicles_tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 291, 411))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bssb_vehicleSearch_lbl = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bssb_vehicleSearch_lbl.sizePolicy().hasHeightForWidth())
        self.bssb_vehicleSearch_lbl.setSizePolicy(sizePolicy)
        self.bssb_vehicleSearch_lbl.setMinimumSize(QtCore.QSize(20, 20))
        self.bssb_vehicleSearch_lbl.setMaximumSize(QtCore.QSize(20, 20))
        self.bssb_vehicleSearch_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bssb_vehicleSearch_lbl.setObjectName("bssb_vehicleSearch_lbl")
        self.horizontalLayout.addWidget(self.bssb_vehicleSearch_lbl)
        self.bssb_vehicleSearch_LE = QtGui.QLineEdit(self.layoutWidget3)
        self.bssb_vehicleSearch_LE.setObjectName("bssb_vehicleSearch_LE")
        self.horizontalLayout.addWidget(self.bssb_vehicleSearch_LE)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.bssb_vehicles_LW = QtGui.QListWidget(self.layoutWidget3)
        self.bssb_vehicles_LW.setObjectName("bssb_vehicles_LW")
        self.verticalLayout_4.addWidget(self.bssb_vehicles_LW)
        self.bssb_assets_tabWidget.addTab(self.Vehicles_tab, "")
        self.verticalLayout_5.addWidget(self.bssb_assets_tabWidget)
        self.gridLayout.addLayout(self.verticalLayout_5, 3, 0, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.bssb_add_PB = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bssb_add_PB.sizePolicy().hasHeightForWidth())
        self.bssb_add_PB.setSizePolicy(sizePolicy)
        self.bssb_add_PB.setMaximumSize(QtCore.QSize(30, 16777215))
        self.bssb_add_PB.setObjectName("bssb_add_PB")
        self.verticalLayout_8.addWidget(self.bssb_add_PB)
        self.bssb_remove_PB = QtGui.QPushButton(self.centralwidget)
        self.bssb_remove_PB.setMaximumSize(QtCore.QSize(30, 16777215))
        self.bssb_remove_PB.setObjectName("bssb_remove_PB")
        self.verticalLayout_8.addWidget(self.bssb_remove_PB)
        self.gridLayout.addLayout(self.verticalLayout_8, 3, 1, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bssb_selectedAsset_lbl = QtGui.QLabel(self.centralwidget)
        self.bssb_selectedAsset_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bssb_selectedAsset_lbl.setObjectName("bssb_selectedAsset_lbl")
        self.verticalLayout_6.addWidget(self.bssb_selectedAsset_lbl)
        self.bssb_selectedAsset_LW = QtGui.QListWidget(self.centralwidget)
        self.bssb_selectedAsset_LW.setObjectName("bssb_selectedAsset_LW")
        self.verticalLayout_6.addWidget(self.bssb_selectedAsset_LW)
        self.gridLayout.addLayout(self.verticalLayout_6, 3, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.bssb_build_PB = QtGui.QPushButton(self.centralwidget)
        self.bssb_build_PB.setMinimumSize(QtCore.QSize(153, 0))
        self.bssb_build_PB.setObjectName("bssb_build_PB")
        self.horizontalLayout_7.addWidget(self.bssb_build_PB)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_7, 5, 0, 1, 3)
        bssb_shotBuilderMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(bssb_shotBuilderMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        bssb_shotBuilderMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(bssb_shotBuilderMainWindow)
        self.statusbar.setObjectName("statusbar")
        bssb_shotBuilderMainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(bssb_shotBuilderMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(bssb_shotBuilderMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(bssb_shotBuilderMainWindow)
        self.bssb_assets_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(bssb_shotBuilderMainWindow)

    def retranslateUi(self, bssb_shotBuilderMainWindow):
        bssb_shotBuilderMainWindow.setWindowTitle(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "BSW Shot Builder MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_logo_lbl.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "BSW LOGO", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_episode_lbl.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Episode:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_episode_LE.setPlaceholderText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Episode", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_sequence_lbl.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Sequence:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_sequence_LE.setPlaceholderText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_shot_lbl.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Shot:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_shot_LE.setPlaceholderText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_startFrame_lbl.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Start Frame:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_endFrame_lbl.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "End Frame:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_riggedAsset_lbl.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Rigged Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_charSearch_lbl.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_charSearch_LE.setPlaceholderText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_assets_tabWidget.setTabText(self.bssb_assets_tabWidget.indexOf(self.Chars_tab), QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_propSearch_lbl.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_propSearch_LE.setPlaceholderText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_assets_tabWidget.setTabText(self.bssb_assets_tabWidget.indexOf(self.Props_tab), QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Prop", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_setSearch_lbl.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_setSearch_LE.setPlaceholderText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_assets_tabWidget.setTabText(self.bssb_assets_tabWidget.indexOf(self.Set_tab), QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_vehicleSearch_lbl.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_vehicleSearch_LE.setPlaceholderText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_assets_tabWidget.setTabText(self.bssb_assets_tabWidget.indexOf(self.Vehicles_tab), QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Vehicle", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_add_PB.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_remove_PB.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_selectedAsset_lbl.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Selected Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.bssb_build_PB.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Build Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("bssb_shotBuilderMainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

