# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:/bsw_programation/01_maya/Pipeline/bsPipe/bsPipe/bs_ui/bsui_anim/bsui_shotManager.ui'
#
# Created: Mon Oct 16 17:19:02 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_bsshm_shotManager_MainWindow(object):
    def setupUi(self, bsshm_shotManager_MainWindow):
        bsshm_shotManager_MainWindow.setObjectName("bsshm_shotManager_MainWindow")
        bsshm_shotManager_MainWindow.resize(800, 700)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(bsshm_shotManager_MainWindow.sizePolicy().hasHeightForWidth())
        bsshm_shotManager_MainWindow.setSizePolicy(sizePolicy)
        bsshm_shotManager_MainWindow.setMinimumSize(QtCore.QSize(800, 700))
        bsshm_shotManager_MainWindow.setMaximumSize(QtCore.QSize(800, 700))
        self.centralwidget = QtGui.QWidget(bsshm_shotManager_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bsshm_logo_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsshm_logo_lbl.sizePolicy().hasHeightForWidth())
        self.bsshm_logo_lbl.setSizePolicy(sizePolicy)
        self.bsshm_logo_lbl.setMinimumSize(QtCore.QSize(0, 40))
        self.bsshm_logo_lbl.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bsshm_logo_lbl.setObjectName("bsshm_logo_lbl")
        self.gridLayout_3.addWidget(self.bsshm_logo_lbl, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bsshm_shot_lblHeader = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsshm_shot_lblHeader.sizePolicy().hasHeightForWidth())
        self.bsshm_shot_lblHeader.setSizePolicy(sizePolicy)
        self.bsshm_shot_lblHeader.setMinimumSize(QtCore.QSize(0, 35))
        self.bsshm_shot_lblHeader.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bsshm_shot_lblHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_shot_lblHeader.setObjectName("bsshm_shot_lblHeader")
        self.gridLayout.addWidget(self.bsshm_shot_lblHeader, 0, 3, 1, 1)
        self.bsshm_sequence_lblHeader = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsshm_sequence_lblHeader.sizePolicy().hasHeightForWidth())
        self.bsshm_sequence_lblHeader.setSizePolicy(sizePolicy)
        self.bsshm_sequence_lblHeader.setMinimumSize(QtCore.QSize(0, 35))
        self.bsshm_sequence_lblHeader.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bsshm_sequence_lblHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_sequence_lblHeader.setObjectName("bsshm_sequence_lblHeader")
        self.gridLayout.addWidget(self.bsshm_sequence_lblHeader, 0, 2, 1, 1)
        self.bsshm_sequence_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsshm_sequence_lbl.sizePolicy().hasHeightForWidth())
        self.bsshm_sequence_lbl.setSizePolicy(sizePolicy)
        self.bsshm_sequence_lbl.setMinimumSize(QtCore.QSize(0, 35))
        self.bsshm_sequence_lbl.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bsshm_sequence_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_sequence_lbl.setObjectName("bsshm_sequence_lbl")
        self.gridLayout.addWidget(self.bsshm_sequence_lbl, 1, 2, 1, 1)
        self.bsshm_shot_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsshm_shot_lbl.sizePolicy().hasHeightForWidth())
        self.bsshm_shot_lbl.setSizePolicy(sizePolicy)
        self.bsshm_shot_lbl.setMinimumSize(QtCore.QSize(0, 35))
        self.bsshm_shot_lbl.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bsshm_shot_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_shot_lbl.setObjectName("bsshm_shot_lbl")
        self.gridLayout.addWidget(self.bsshm_shot_lbl, 1, 3, 1, 1)
        self.bsshm_episode_lblHeader = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsshm_episode_lblHeader.sizePolicy().hasHeightForWidth())
        self.bsshm_episode_lblHeader.setSizePolicy(sizePolicy)
        self.bsshm_episode_lblHeader.setMinimumSize(QtCore.QSize(0, 35))
        self.bsshm_episode_lblHeader.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bsshm_episode_lblHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_episode_lblHeader.setObjectName("bsshm_episode_lblHeader")
        self.gridLayout.addWidget(self.bsshm_episode_lblHeader, 0, 1, 1, 1)
        self.bsshm_episode_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsshm_episode_lbl.sizePolicy().hasHeightForWidth())
        self.bsshm_episode_lbl.setSizePolicy(sizePolicy)
        self.bsshm_episode_lbl.setMinimumSize(QtCore.QSize(0, 35))
        self.bsshm_episode_lbl.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bsshm_episode_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_episode_lbl.setObjectName("bsshm_episode_lbl")
        self.gridLayout.addWidget(self.bsshm_episode_lbl, 1, 1, 1, 1)
        self.bsshm_fileType_lblHeader = QtGui.QLabel(self.centralwidget)
        self.bsshm_fileType_lblHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_fileType_lblHeader.setObjectName("bsshm_fileType_lblHeader")
        self.gridLayout.addWidget(self.bsshm_fileType_lblHeader, 0, 0, 1, 1)
        self.bsshm_fileType_lbl = QtGui.QLabel(self.centralwidget)
        self.bsshm_fileType_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_fileType_lbl.setObjectName("bsshm_fileType_lbl")
        self.gridLayout.addWidget(self.bsshm_fileType_lbl, 1, 0, 1, 1)
        self.bsshm_fixFrameRange_lbl = QtGui.QLabel(self.centralwidget)
        self.bsshm_fixFrameRange_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_fixFrameRange_lbl.setObjectName("bsshm_fixFrameRange_lbl")
        self.gridLayout.addWidget(self.bsshm_fixFrameRange_lbl, 0, 4, 1, 1)
        self.bsshm_fixFrameRange_PB = QtGui.QPushButton(self.centralwidget)
        self.bsshm_fixFrameRange_PB.setObjectName("bsshm_fixFrameRange_PB")
        self.gridLayout.addWidget(self.bsshm_fixFrameRange_PB, 1, 4, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 3, 0, 1, 1)
        self.bsshm_tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.bsshm_tabWidget.setObjectName("bsshm_tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 8, 761, 471))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bsshm_CA_vehicle_lbl = QtGui.QLabel(self.layoutWidget)
        self.bsshm_CA_vehicle_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_CA_vehicle_lbl.setObjectName("bsshm_CA_vehicle_lbl")
        self.gridLayout_2.addWidget(self.bsshm_CA_vehicle_lbl, 0, 3, 1, 1)
        self.bsshm_CA_prop_LW = QtGui.QListWidget(self.layoutWidget)
        self.bsshm_CA_prop_LW.setObjectName("bsshm_CA_prop_LW")
        self.gridLayout_2.addWidget(self.bsshm_CA_prop_LW, 2, 1, 1, 1)
        self.bsshm_CA_vehicle_LW = QtGui.QListWidget(self.layoutWidget)
        self.bsshm_CA_vehicle_LW.setObjectName("bsshm_CA_vehicle_LW")
        self.gridLayout_2.addWidget(self.bsshm_CA_vehicle_LW, 2, 3, 1, 1)
        self.bsshm_CA_set_lbl = QtGui.QLabel(self.layoutWidget)
        self.bsshm_CA_set_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_CA_set_lbl.setObjectName("bsshm_CA_set_lbl")
        self.gridLayout_2.addWidget(self.bsshm_CA_set_lbl, 0, 2, 1, 1)
        self.bsshm_CA_char_LW = QtGui.QListWidget(self.layoutWidget)
        self.bsshm_CA_char_LW.setObjectName("bsshm_CA_char_LW")
        self.gridLayout_2.addWidget(self.bsshm_CA_char_LW, 2, 0, 1, 1)
        self.bsshm_CA_char_lbl = QtGui.QLabel(self.layoutWidget)
        self.bsshm_CA_char_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_CA_char_lbl.setObjectName("bsshm_CA_char_lbl")
        self.gridLayout_2.addWidget(self.bsshm_CA_char_lbl, 0, 0, 1, 1)
        self.bsshm_CA_prop_lbl = QtGui.QLabel(self.layoutWidget)
        self.bsshm_CA_prop_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_CA_prop_lbl.setObjectName("bsshm_CA_prop_lbl")
        self.gridLayout_2.addWidget(self.bsshm_CA_prop_lbl, 0, 1, 1, 1)
        self.bsshm_CA_set_LW = QtGui.QListWidget(self.layoutWidget)
        self.bsshm_CA_set_LW.setObjectName("bsshm_CA_set_LW")
        self.gridLayout_2.addWidget(self.bsshm_CA_set_LW, 2, 2, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.bsshm_CA_setSearch_LE = QtGui.QLineEdit(self.layoutWidget)
        self.bsshm_CA_setSearch_LE.setObjectName("bsshm_CA_setSearch_LE")
        self.horizontalLayout_11.addWidget(self.bsshm_CA_setSearch_LE)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 1, 2, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.bsshm_CA_vehicleSearch_LE = QtGui.QLineEdit(self.layoutWidget)
        self.bsshm_CA_vehicleSearch_LE.setObjectName("bsshm_CA_vehicleSearch_LE")
        self.horizontalLayout_12.addWidget(self.bsshm_CA_vehicleSearch_LE)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 1, 3, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.bsshm_CA_charSearch_LE = QtGui.QLineEdit(self.layoutWidget)
        self.bsshm_CA_charSearch_LE.setObjectName("bsshm_CA_charSearch_LE")
        self.horizontalLayout_9.addWidget(self.bsshm_CA_charSearch_LE)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.bsshm_CA_propSearch_LE = QtGui.QLineEdit(self.layoutWidget)
        self.bsshm_CA_propSearch_LE.setObjectName("bsshm_CA_propSearch_LE")
        self.horizontalLayout_10.addWidget(self.bsshm_CA_propSearch_LE)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 1, 1, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.bsshm_CA_charSelAll_cBox = QtGui.QCheckBox(self.layoutWidget)
        self.bsshm_CA_charSelAll_cBox.setObjectName("bsshm_CA_charSelAll_cBox")
        self.horizontalLayout_16.addWidget(self.bsshm_CA_charSelAll_cBox)
        self.bsshm_CA_charClearAll_cBox = QtGui.QCheckBox(self.layoutWidget)
        self.bsshm_CA_charClearAll_cBox.setObjectName("bsshm_CA_charClearAll_cBox")
        self.horizontalLayout_16.addWidget(self.bsshm_CA_charClearAll_cBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 3, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.bsshm_CA_propSelAll_cBox = QtGui.QCheckBox(self.layoutWidget)
        self.bsshm_CA_propSelAll_cBox.setObjectName("bsshm_CA_propSelAll_cBox")
        self.horizontalLayout_13.addWidget(self.bsshm_CA_propSelAll_cBox)
        self.bsshm_CA_propClearAll_cBox = QtGui.QCheckBox(self.layoutWidget)
        self.bsshm_CA_propClearAll_cBox.setObjectName("bsshm_CA_propClearAll_cBox")
        self.horizontalLayout_13.addWidget(self.bsshm_CA_propClearAll_cBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 3, 1, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.bsshm_CA_setSelAll_cBox = QtGui.QCheckBox(self.layoutWidget)
        self.bsshm_CA_setSelAll_cBox.setObjectName("bsshm_CA_setSelAll_cBox")
        self.horizontalLayout_14.addWidget(self.bsshm_CA_setSelAll_cBox)
        self.bsshm_CA_setClearAll_cBox = QtGui.QCheckBox(self.layoutWidget)
        self.bsshm_CA_setClearAll_cBox.setObjectName("bsshm_CA_setClearAll_cBox")
        self.horizontalLayout_14.addWidget(self.bsshm_CA_setClearAll_cBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 3, 2, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.bsshm_CA_vehicleSelAll_cBox = QtGui.QCheckBox(self.layoutWidget)
        self.bsshm_CA_vehicleSelAll_cBox.setObjectName("bsshm_CA_vehicleSelAll_cBox")
        self.horizontalLayout_15.addWidget(self.bsshm_CA_vehicleSelAll_cBox)
        self.bsshm_CA_vehicleClearAll_cBox = QtGui.QCheckBox(self.layoutWidget)
        self.bsshm_CA_vehicleClearAll_cBox.setObjectName("bsshm_CA_vehicleClearAll_cBox")
        self.horizontalLayout_15.addWidget(self.bsshm_CA_vehicleClearAll_cBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 3, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.line_5 = QtGui.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_7.addWidget(self.line_5)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.bsshm_CA_exportCache_PB = QtGui.QPushButton(self.layoutWidget)
        self.bsshm_CA_exportCache_PB.setObjectName("bsshm_CA_exportCache_PB")
        self.horizontalLayout_18.addWidget(self.bsshm_CA_exportCache_PB)
        self.bsshm_CA_exportAnim_PB = QtGui.QPushButton(self.layoutWidget)
        self.bsshm_CA_exportAnim_PB.setObjectName("bsshm_CA_exportAnim_PB")
        self.horizontalLayout_18.addWidget(self.bsshm_CA_exportAnim_PB)
        self.bsshm_CA_exportCamera_PB = QtGui.QPushButton(self.layoutWidget)
        self.bsshm_CA_exportCamera_PB.setObjectName("bsshm_CA_exportCamera_PB")
        self.horizontalLayout_18.addWidget(self.bsshm_CA_exportCamera_PB)
        spacerItem = QtGui.QSpacerItem(120, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.bsshm_CA_playblast_PB = QtGui.QPushButton(self.layoutWidget)
        self.bsshm_CA_playblast_PB.setObjectName("bsshm_CA_playblast_PB")
        self.horizontalLayout_17.addWidget(self.bsshm_CA_playblast_PB)
        self.bsshm_CA_playblastBatch_cBox = QtGui.QCheckBox(self.layoutWidget)
        self.bsshm_CA_playblastBatch_cBox.setObjectName("bsshm_CA_playblastBatch_cBox")
        self.horizontalLayout_17.addWidget(self.bsshm_CA_playblastBatch_cBox)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.line_4 = QtGui.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_7.addWidget(self.line_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.bsshm_CA_publishSceneAs_lbl = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsshm_CA_publishSceneAs_lbl.sizePolicy().hasHeightForWidth())
        self.bsshm_CA_publishSceneAs_lbl.setSizePolicy(sizePolicy)
        self.bsshm_CA_publishSceneAs_lbl.setMinimumSize(QtCore.QSize(0, 30))
        self.bsshm_CA_publishSceneAs_lbl.setObjectName("bsshm_CA_publishSceneAs_lbl")
        self.horizontalLayout_8.addWidget(self.bsshm_CA_publishSceneAs_lbl)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.bsshm_CA_layout_PB = QtGui.QPushButton(self.layoutWidget)
        self.bsshm_CA_layout_PB.setObjectName("bsshm_CA_layout_PB")
        self.horizontalLayout_7.addWidget(self.bsshm_CA_layout_PB)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.bsshm_CA_animation_PB = QtGui.QPushButton(self.layoutWidget)
        self.bsshm_CA_animation_PB.setObjectName("bsshm_CA_animation_PB")
        self.horizontalLayout_7.addWidget(self.bsshm_CA_animation_PB)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.line_3 = QtGui.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_7.addWidget(self.line_3)
        self.bsshm_tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(8, 5, 761, 476))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.bsshm_assets_tabWidget = QtGui.QTabWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsshm_assets_tabWidget.sizePolicy().hasHeightForWidth())
        self.bsshm_assets_tabWidget.setSizePolicy(sizePolicy)
        self.bsshm_assets_tabWidget.setMinimumSize(QtCore.QSize(301, 441))
        self.bsshm_assets_tabWidget.setMaximumSize(QtCore.QSize(301, 441))
        self.bsshm_assets_tabWidget.setObjectName("bsshm_assets_tabWidget")
        self.Chars_tab = QtGui.QWidget()
        self.Chars_tab.setObjectName("Chars_tab")
        self.layoutWidget_2 = QtGui.QWidget(self.Chars_tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 291, 411))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bsshm_charSearch_LE = QtGui.QLineEdit(self.layoutWidget_2)
        self.bsshm_charSearch_LE.setObjectName("bsshm_charSearch_LE")
        self.horizontalLayout_4.addWidget(self.bsshm_charSearch_LE)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.bsshm_chars_LW = QtGui.QListWidget(self.layoutWidget_2)
        self.bsshm_chars_LW.setObjectName("bsshm_chars_LW")
        self.verticalLayout.addWidget(self.bsshm_chars_LW)
        self.bsshm_assets_tabWidget.addTab(self.Chars_tab, "")
        self.Props_tab = QtGui.QWidget()
        self.Props_tab.setObjectName("Props_tab")
        self.layoutWidget_3 = QtGui.QWidget(self.Props_tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 0, 291, 411))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bsshm_propSearch_LE = QtGui.QLineEdit(self.layoutWidget_3)
        self.bsshm_propSearch_LE.setObjectName("bsshm_propSearch_LE")
        self.horizontalLayout_3.addWidget(self.bsshm_propSearch_LE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.bsshm_props_LW = QtGui.QListWidget(self.layoutWidget_3)
        self.bsshm_props_LW.setObjectName("bsshm_props_LW")
        self.verticalLayout_2.addWidget(self.bsshm_props_LW)
        self.bsshm_assets_tabWidget.addTab(self.Props_tab, "")
        self.Set_tab = QtGui.QWidget()
        self.Set_tab.setObjectName("Set_tab")
        self.layoutWidget_4 = QtGui.QWidget(self.Set_tab)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 0, 291, 411))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bsshm_setSearch_LE = QtGui.QLineEdit(self.layoutWidget_4)
        self.bsshm_setSearch_LE.setObjectName("bsshm_setSearch_LE")
        self.horizontalLayout_2.addWidget(self.bsshm_setSearch_LE)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.bsshm_set_LW = QtGui.QListWidget(self.layoutWidget_4)
        self.bsshm_set_LW.setObjectName("bsshm_set_LW")
        self.verticalLayout_3.addWidget(self.bsshm_set_LW)
        self.bsshm_assets_tabWidget.addTab(self.Set_tab, "")
        self.Vehicles_tab = QtGui.QWidget()
        self.Vehicles_tab.setObjectName("Vehicles_tab")
        self.layoutWidget_5 = QtGui.QWidget(self.Vehicles_tab)
        self.layoutWidget_5.setGeometry(QtCore.QRect(0, 0, 291, 411))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bsshm_vehicleSearch_LE = QtGui.QLineEdit(self.layoutWidget_5)
        self.bsshm_vehicleSearch_LE.setObjectName("bsshm_vehicleSearch_LE")
        self.horizontalLayout.addWidget(self.bsshm_vehicleSearch_LE)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.bsshm_vehicles_LW = QtGui.QListWidget(self.layoutWidget_5)
        self.bsshm_vehicles_LW.setObjectName("bsshm_vehicles_LW")
        self.verticalLayout_4.addWidget(self.bsshm_vehicles_LW)
        self.bsshm_assets_tabWidget.addTab(self.Vehicles_tab, "")
        self.horizontalLayout_19.addWidget(self.bsshm_assets_tabWidget)
        spacerItem6 = QtGui.QSpacerItem(45, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bsshm_add_PB = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsshm_add_PB.sizePolicy().hasHeightForWidth())
        self.bsshm_add_PB.setSizePolicy(sizePolicy)
        self.bsshm_add_PB.setMaximumSize(QtCore.QSize(30, 16777215))
        self.bsshm_add_PB.setObjectName("bsshm_add_PB")
        self.verticalLayout_5.addWidget(self.bsshm_add_PB)
        self.bsshm_remove_PB = QtGui.QPushButton(self.layoutWidget1)
        self.bsshm_remove_PB.setMaximumSize(QtCore.QSize(30, 16777215))
        self.bsshm_remove_PB.setObjectName("bsshm_remove_PB")
        self.verticalLayout_5.addWidget(self.bsshm_remove_PB)
        self.horizontalLayout_19.addLayout(self.verticalLayout_5)
        spacerItem7 = QtGui.QSpacerItem(45, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem7)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bsshm_selectedAsset_lbl = QtGui.QLabel(self.layoutWidget1)
        self.bsshm_selectedAsset_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsshm_selectedAsset_lbl.setObjectName("bsshm_selectedAsset_lbl")
        self.verticalLayout_6.addWidget(self.bsshm_selectedAsset_lbl)
        self.bsshm_selectedAsset_LW = QtGui.QListWidget(self.layoutWidget1)
        self.bsshm_selectedAsset_LW.setObjectName("bsshm_selectedAsset_LW")
        self.verticalLayout_6.addWidget(self.bsshm_selectedAsset_LW)
        self.horizontalLayout_19.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem8)
        self.bsshm_addSelectedAssetInScene_PB = QtGui.QPushButton(self.layoutWidget1)
        self.bsshm_addSelectedAssetInScene_PB.setObjectName("bsshm_addSelectedAssetInScene_PB")
        self.horizontalLayout_20.addWidget(self.bsshm_addSelectedAssetInScene_PB)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.bsshm_tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget2 = QtGui.QWidget(self.tab_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 10, 771, 461))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.bsshm_currentAssetInScene_lbl = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsshm_currentAssetInScene_lbl.sizePolicy().hasHeightForWidth())
        self.bsshm_currentAssetInScene_lbl.setSizePolicy(sizePolicy)
        self.bsshm_currentAssetInScene_lbl.setMinimumSize(QtCore.QSize(0, 25))
        self.bsshm_currentAssetInScene_lbl.setObjectName("bsshm_currentAssetInScene_lbl")
        self.horizontalLayout_6.addWidget(self.bsshm_currentAssetInScene_lbl)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.bsshm_currentAsset_LW = QtGui.QListWidget(self.layoutWidget2)
        self.bsshm_currentAsset_LW.setObjectName("bsshm_currentAsset_LW")
        self.verticalLayout_9.addWidget(self.bsshm_currentAsset_LW)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.bsshm_removeSelectedAssets_PB = QtGui.QPushButton(self.layoutWidget2)
        self.bsshm_removeSelectedAssets_PB.setObjectName("bsshm_removeSelectedAssets_PB")
        self.horizontalLayout_5.addWidget(self.bsshm_removeSelectedAssets_PB)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.bsshm_tabWidget.addTab(self.tab_3, "")
        self.gridLayout_3.addWidget(self.bsshm_tabWidget, 4, 0, 1, 1)
        bsshm_shotManager_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(bsshm_shotManager_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        bsshm_shotManager_MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(bsshm_shotManager_MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(bsshm_shotManager_MainWindow)
        self.bsshm_tabWidget.setCurrentIndex(0)
        self.bsshm_assets_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(bsshm_shotManager_MainWindow)

    def retranslateUi(self, bsshm_shotManager_MainWindow):
        bsshm_shotManager_MainWindow.setWindowTitle(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "BSW Shot Manager MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_logo_lbl.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "BSW_LOGO", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_shot_lblHeader.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_sequence_lblHeader.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_sequence_lbl.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Not Exist", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_shot_lbl.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Not Exist", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_episode_lblHeader.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Episode", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_episode_lbl.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Not Exist", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_fileType_lblHeader.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "File Type", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_fileType_lbl.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Not Exist", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_fixFrameRange_lbl.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Fix Frame Range", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_fixFrameRange_PB.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Fix Frame Range", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_vehicle_lbl.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Vehicle", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_set_lbl.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_char_lbl.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_prop_lbl.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Prop", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_setSearch_LE.setPlaceholderText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_vehicleSearch_LE.setPlaceholderText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_charSearch_LE.setPlaceholderText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_propSearch_LE.setPlaceholderText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_charSelAll_cBox.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Selecte All", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_charClearAll_cBox.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_propSelAll_cBox.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Selecte All", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_propClearAll_cBox.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_setSelAll_cBox.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Selecte All", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_setClearAll_cBox.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_vehicleSelAll_cBox.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Selecte All", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_vehicleClearAll_cBox.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_exportCache_PB.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Export Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_exportAnim_PB.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Export Anim", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_exportCamera_PB.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Export Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_playblast_PB.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Create Playblast", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_playblastBatch_cBox.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Use Batch", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_publishSceneAs_lbl.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Publish Scene As", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_layout_PB.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_CA_animation_PB.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_tabWidget.setTabText(self.bsshm_tabWidget.indexOf(self.tab), QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Current Assets In Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_charSearch_LE.setPlaceholderText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_assets_tabWidget.setTabText(self.bsshm_assets_tabWidget.indexOf(self.Chars_tab), QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_propSearch_LE.setPlaceholderText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_assets_tabWidget.setTabText(self.bsshm_assets_tabWidget.indexOf(self.Props_tab), QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Prop", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_setSearch_LE.setPlaceholderText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_assets_tabWidget.setTabText(self.bsshm_assets_tabWidget.indexOf(self.Set_tab), QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_vehicleSearch_LE.setPlaceholderText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_assets_tabWidget.setTabText(self.bsshm_assets_tabWidget.indexOf(self.Vehicles_tab), QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Vehicle", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_add_PB.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_remove_PB.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_selectedAsset_lbl.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Selected Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_addSelectedAssetInScene_PB.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Add Selected Asset In Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_tabWidget.setTabText(self.bsshm_tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Add New Asset In Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_currentAssetInScene_lbl.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Current Asset Used In Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_removeSelectedAssets_PB.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Remove Selected Asset References From Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.bsshm_tabWidget.setTabText(self.bsshm_tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Remove Current Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("bsshm_shotManager_MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

