# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:/bsw_programation/01_maya/Pipeline/bsPipe/bsPipe/bs_ui/bsui_asset/bsui_createRig.ui'
#
# Created: Fri Sep 08 15:34:24 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_bscr_createRig_MW(object):
    def setupUi(self, bscr_createRig_MW):
        bscr_createRig_MW.setObjectName("bscr_createRig_MW")
        bscr_createRig_MW.resize(1094, 629)
        self.centralwidget = QtGui.QWidget(bscr_createRig_MW)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bscr_icon_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bscr_icon_lbl.sizePolicy().hasHeightForWidth())
        self.bscr_icon_lbl.setSizePolicy(sizePolicy)
        self.bscr_icon_lbl.setMinimumSize(QtCore.QSize(800, 40))
        self.bscr_icon_lbl.setObjectName("bscr_icon_lbl")
        self.verticalLayout_3.addWidget(self.bscr_icon_lbl)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.bscr_assetNames_lw = QtGui.QListWidget(self.centralwidget)
        self.bscr_assetNames_lw.setObjectName("bscr_assetNames_lw")
        self.gridLayout_2.addWidget(self.bscr_assetNames_lw, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.bscr_assetTypes_lw = QtGui.QListWidget(self.centralwidget)
        self.bscr_assetTypes_lw.setObjectName("bscr_assetTypes_lw")
        QtGui.QListWidgetItem(self.bscr_assetTypes_lw)
        QtGui.QListWidgetItem(self.bscr_assetTypes_lw)
        QtGui.QListWidgetItem(self.bscr_assetTypes_lw)
        QtGui.QListWidgetItem(self.bscr_assetTypes_lw)
        QtGui.QListWidgetItem(self.bscr_assetTypes_lw)
        self.gridLayout_2.addWidget(self.bscr_assetTypes_lw, 1, 0, 1, 1)
        self.bscr_assetFilesAndVer_lw = QtGui.QListWidget(self.centralwidget)
        self.bscr_assetFilesAndVer_lw.setObjectName("bscr_assetFilesAndVer_lw")
        self.gridLayout_2.addWidget(self.bscr_assetFilesAndVer_lw, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.bscr_createBase_pb = QtGui.QPushButton(self.centralwidget)
        self.bscr_createBase_pb.setObjectName("bscr_createBase_pb")
        self.verticalLayout_2.addWidget(self.bscr_createBase_pb)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.bscr_snapshot_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bscr_snapshot_lbl.sizePolicy().hasHeightForWidth())
        self.bscr_snapshot_lbl.setSizePolicy(sizePolicy)
        self.bscr_snapshot_lbl.setMinimumSize(QtCore.QSize(0, 106))
        self.bscr_snapshot_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bscr_snapshot_lbl.setObjectName("bscr_snapshot_lbl")
        self.verticalLayout.addWidget(self.bscr_snapshot_lbl)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bscr_assetName_lbl = QtGui.QLabel(self.centralwidget)
        self.bscr_assetName_lbl.setObjectName("bscr_assetName_lbl")
        self.gridLayout.addWidget(self.bscr_assetName_lbl, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.bscr_assetType_lbl = QtGui.QLabel(self.centralwidget)
        self.bscr_assetType_lbl.setObjectName("bscr_assetType_lbl")
        self.gridLayout.addWidget(self.bscr_assetType_lbl, 2, 1, 1, 1)
        self.bscr_assetShort_lbl = QtGui.QLabel(self.centralwidget)
        self.bscr_assetShort_lbl.setObjectName("bscr_assetShort_lbl")
        self.gridLayout.addWidget(self.bscr_assetShort_lbl, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.bscr_assetGrade_lbl = QtGui.QLabel(self.centralwidget)
        self.bscr_assetGrade_lbl.setObjectName("bscr_assetGrade_lbl")
        self.gridLayout.addWidget(self.bscr_assetGrade_lbl, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.bscr_versionInfo_lw = QtGui.QListWidget(self.centralwidget)
        self.bscr_versionInfo_lw.setObjectName("bscr_versionInfo_lw")
        self.verticalLayout.addWidget(self.bscr_versionInfo_lw)
        self.bscr_refresh_pb = QtGui.QPushButton(self.centralwidget)
        self.bscr_refresh_pb.setObjectName("bscr_refresh_pb")
        self.verticalLayout.addWidget(self.bscr_refresh_pb)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 1, 1)
        bscr_createRig_MW.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(bscr_createRig_MW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1094, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        bscr_createRig_MW.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(bscr_createRig_MW)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(bscr_createRig_MW)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(bscr_createRig_MW)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), bscr_createRig_MW.close)
        QtCore.QMetaObject.connectSlotsByName(bscr_createRig_MW)

    def retranslateUi(self, bscr_createRig_MW):
        bscr_createRig_MW.setWindowTitle(QtGui.QApplication.translate("bscr_createRig_MW", "Create Rig Base", None, QtGui.QApplication.UnicodeUTF8))
        self.bscr_icon_lbl.setText(QtGui.QApplication.translate("bscr_createRig_MW", "Create Rig Base", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("bscr_createRig_MW", "Asset Model", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("bscr_createRig_MW", "Asset Type", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.bscr_assetTypes_lw.isSortingEnabled()
        self.bscr_assetTypes_lw.setSortingEnabled(False)
        self.bscr_assetTypes_lw.item(0).setText(QtGui.QApplication.translate("bscr_createRig_MW", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.bscr_assetTypes_lw.item(1).setText(QtGui.QApplication.translate("bscr_createRig_MW", "Prop", None, QtGui.QApplication.UnicodeUTF8))
        self.bscr_assetTypes_lw.item(2).setText(QtGui.QApplication.translate("bscr_createRig_MW", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.bscr_assetTypes_lw.item(3).setText(QtGui.QApplication.translate("bscr_createRig_MW", "SetElement", None, QtGui.QApplication.UnicodeUTF8))
        self.bscr_assetTypes_lw.item(4).setText(QtGui.QApplication.translate("bscr_createRig_MW", "Vehicle", None, QtGui.QApplication.UnicodeUTF8))
        self.bscr_assetTypes_lw.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(QtGui.QApplication.translate("bscr_createRig_MW", "Asset Model File And Versions", None, QtGui.QApplication.UnicodeUTF8))
        self.bscr_createBase_pb.setText(QtGui.QApplication.translate("bscr_createRig_MW", "Create Rig Base", None, QtGui.QApplication.UnicodeUTF8))
        self.bscr_snapshot_lbl.setText(QtGui.QApplication.translate("bscr_createRig_MW", "SnapShot", None, QtGui.QApplication.UnicodeUTF8))
        self.bscr_assetName_lbl.setText(QtGui.QApplication.translate("bscr_createRig_MW", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("bscr_createRig_MW", "Asset Name:-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("bscr_createRig_MW", "Asset Type:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bscr_assetType_lbl.setText(QtGui.QApplication.translate("bscr_createRig_MW", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.bscr_assetShort_lbl.setText(QtGui.QApplication.translate("bscr_createRig_MW", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("bscr_createRig_MW", "Asset Episode:-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("bscr_createRig_MW", "Asset Grade:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bscr_assetGrade_lbl.setText(QtGui.QApplication.translate("bscr_createRig_MW", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("bscr_createRig_MW", "Info:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bscr_refresh_pb.setText(QtGui.QApplication.translate("bscr_createRig_MW", "Refersh", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("bscr_createRig_MW", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("bscr_createRig_MW", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("bscr_createRig_MW", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("bscr_createRig_MW", "About", None, QtGui.QApplication.UnicodeUTF8))

