# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:/bsw_programation/01_maya/Pipeline/bsPipe/bsPipe/bs_ui/bsui_asset/bsui_setManager.ui'
#
# Created: Mon Sep 11 16:01:25 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_bssm_setManager_MW(object):
    def setupUi(self, bssm_setManager_MW):
        bssm_setManager_MW.setObjectName("bssm_setManager_MW")
        bssm_setManager_MW.resize(746, 667)
        self.centralwidget = QtGui.QWidget(bssm_setManager_MW)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.bssm_category_lbl = QtGui.QLabel(self.centralwidget)
        self.bssm_category_lbl.setText("")
        self.bssm_category_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bssm_category_lbl.setObjectName("bssm_category_lbl")
        self.gridLayout_2.addWidget(self.bssm_category_lbl, 1, 0, 1, 1)
        self.bssm_assetType_lbl = QtGui.QLabel(self.centralwidget)
        self.bssm_assetType_lbl.setText("")
        self.bssm_assetType_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bssm_assetType_lbl.setObjectName("bssm_assetType_lbl")
        self.gridLayout_2.addWidget(self.bssm_assetType_lbl, 1, 1, 1, 1)
        self.bssm_assetName_lbl = QtGui.QLabel(self.centralwidget)
        self.bssm_assetName_lbl.setText("")
        self.bssm_assetName_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bssm_assetName_lbl.setObjectName("bssm_assetName_lbl")
        self.gridLayout_2.addWidget(self.bssm_assetName_lbl, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.bssm_setElementLib_LW = QtGui.QListWidget(self.centralwidget)
        self.bssm_setElementLib_LW.setObjectName("bssm_setElementLib_LW")
        self.verticalLayout.addWidget(self.bssm_setElementLib_LW)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bssm_addElem_PB = QtGui.QPushButton(self.centralwidget)
        self.bssm_addElem_PB.setMaximumSize(QtCore.QSize(23, 16777215))
        self.bssm_addElem_PB.setObjectName("bssm_addElem_PB")
        self.verticalLayout_4.addWidget(self.bssm_addElem_PB)
        self.bssm_remElem_PB = QtGui.QPushButton(self.centralwidget)
        self.bssm_remElem_PB.setMaximumSize(QtCore.QSize(23, 16777215))
        self.bssm_remElem_PB.setObjectName("bssm_remElem_PB")
        self.verticalLayout_4.addWidget(self.bssm_remElem_PB)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.bssm_selectedItems_LW = QtGui.QListWidget(self.centralwidget)
        self.bssm_selectedItems_LW.setObjectName("bssm_selectedItems_LW")
        self.verticalLayout_2.addWidget(self.bssm_selectedItems_LW)
        self.bssm_addElemInScene_PB = QtGui.QPushButton(self.centralwidget)
        self.bssm_addElemInScene_PB.setObjectName("bssm_addElemInScene_PB")
        self.verticalLayout_2.addWidget(self.bssm_addElemInScene_PB)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.bssm_test_PB = QtGui.QPushButton(self.centralwidget)
        self.bssm_test_PB.setMaximumSize(QtCore.QSize(23, 16777215))
        self.bssm_test_PB.setText("")
        self.bssm_test_PB.setObjectName("bssm_test_PB")
        self.horizontalLayout.addWidget(self.bssm_test_PB)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.bssm_currentSetElem_LW = QtGui.QListWidget(self.centralwidget)
        self.bssm_currentSetElem_LW.setObjectName("bssm_currentSetElem_LW")
        self.verticalLayout_3.addWidget(self.bssm_currentSetElem_LW)
        self.bssm_removeRef_PB = QtGui.QPushButton(self.centralwidget)
        self.bssm_removeRef_PB.setObjectName("bssm_removeRef_PB")
        self.verticalLayout_3.addWidget(self.bssm_removeRef_PB)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bssm_refresh_PB = QtGui.QPushButton(self.centralwidget)
        self.bssm_refresh_PB.setObjectName("bssm_refresh_PB")
        self.horizontalLayout_3.addWidget(self.bssm_refresh_PB)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 4, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 5, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 6, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.bssm_exportGPU_PB = QtGui.QPushButton(self.centralwidget)
        self.bssm_exportGPU_PB.setObjectName("bssm_exportGPU_PB")
        self.horizontalLayout_2.addWidget(self.bssm_exportGPU_PB)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem3, 8, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 9, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 10, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.bssm_GPUcachePath_LE = QtGui.QLineEdit(self.centralwidget)
        self.bssm_GPUcachePath_LE.setObjectName("bssm_GPUcachePath_LE")
        self.gridLayout.addWidget(self.bssm_GPUcachePath_LE, 0, 1, 1, 1)
        self.bssm_GPUcachePath_PB = QtGui.QPushButton(self.centralwidget)
        self.bssm_GPUcachePath_PB.setMaximumSize(QtCore.QSize(25, 16777215))
        self.bssm_GPUcachePath_PB.setObjectName("bssm_GPUcachePath_PB")
        self.gridLayout.addWidget(self.bssm_GPUcachePath_PB, 0, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.bssm_GPUfilePath_LE = QtGui.QLineEdit(self.centralwidget)
        self.bssm_GPUfilePath_LE.setObjectName("bssm_GPUfilePath_LE")
        self.gridLayout.addWidget(self.bssm_GPUfilePath_LE, 1, 1, 1, 1)
        self.bssm_GPUfilePath_PB = QtGui.QPushButton(self.centralwidget)
        self.bssm_GPUfilePath_PB.setMaximumSize(QtCore.QSize(25, 16777215))
        self.bssm_GPUfilePath_PB.setObjectName("bssm_GPUfilePath_PB")
        self.gridLayout.addWidget(self.bssm_GPUfilePath_PB, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 11, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem4, 12, 0, 1, 1)
        bssm_setManager_MW.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(bssm_setManager_MW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 746, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        bssm_setManager_MW.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(bssm_setManager_MW)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(bssm_setManager_MW)
        QtCore.QMetaObject.connectSlotsByName(bssm_setManager_MW)

    def retranslateUi(self, bssm_setManager_MW):
        bssm_setManager_MW.setWindowTitle(QtGui.QApplication.translate("bssm_setManager_MW", "BSW Set Manager -- Main Window", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Manage Set Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Asset Department", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Asset Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Asset Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Set Elements Library", None, QtGui.QApplication.UnicodeUTF8))
        self.bssm_addElem_PB.setText(QtGui.QApplication.translate("bssm_setManager_MW", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.bssm_remElem_PB.setText(QtGui.QApplication.translate("bssm_setManager_MW", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Selected Set Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.bssm_addElemInScene_PB.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Add Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Current Set Elements In Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.bssm_removeRef_PB.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Remove Current Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.bssm_refresh_PB.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Export GPU", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Expoprt GPU of Current Set:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bssm_exportGPU_PB.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Export GPU", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Exported GPU Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("bssm_setManager_MW", "GPU Cache Path:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bssm_GPUcachePath_PB.setText(QtGui.QApplication.translate("bssm_setManager_MW", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("bssm_setManager_MW", "GPU File Path:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bssm_GPUfilePath_PB.setText(QtGui.QApplication.translate("bssm_setManager_MW", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("bssm_setManager_MW", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("bssm_setManager_MW", "Exit", None, QtGui.QApplication.UnicodeUTF8))

