# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:/bsw_programation/01_maya/Pipeline/bsPipe/bsPipe/bs_ui/bsui_asset/bsui_assetCreate.ui'
#
# Created: Wed Sep 06 12:38:30 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_bsag_assetGenerate_MW(object):
    def setupUi(self, bsag_assetGenerate_MW):
        bsag_assetGenerate_MW.setObjectName("bsag_assetGenerate_MW")
        bsag_assetGenerate_MW.resize(519, 307)
        self.centralwidget = QtGui.QWidget(bsag_assetGenerate_MW)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bsag_createAsset_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsag_createAsset_pb.sizePolicy().hasHeightForWidth())
        self.bsag_createAsset_pb.setSizePolicy(sizePolicy)
        self.bsag_createAsset_pb.setMinimumSize(QtCore.QSize(0, 50))
        self.bsag_createAsset_pb.setObjectName("bsag_createAsset_pb")
        self.gridLayout_2.addWidget(self.bsag_createAsset_pb, 2, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bsag_assetGrade_comboBox = QtGui.QComboBox(self.centralwidget)
        self.bsag_assetGrade_comboBox.setObjectName("bsag_assetGrade_comboBox")
        self.bsag_assetGrade_comboBox.addItem("")
        self.bsag_assetGrade_comboBox.addItem("")
        self.bsag_assetGrade_comboBox.addItem("")
        self.gridLayout.addWidget(self.bsag_assetGrade_comboBox, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.bsag_assetName_LE = QtGui.QLineEdit(self.centralwidget)
        self.bsag_assetName_LE.setToolTip("")
        self.bsag_assetName_LE.setWhatsThis("")
        self.bsag_assetName_LE.setAccessibleName("")
        self.bsag_assetName_LE.setInputMask("")
        self.bsag_assetName_LE.setText("")
        self.bsag_assetName_LE.setObjectName("bsag_assetName_LE")
        self.gridLayout.addWidget(self.bsag_assetName_LE, 1, 1, 1, 1)
        self.bsag_assetType_comboBox = QtGui.QComboBox(self.centralwidget)
        self.bsag_assetType_comboBox.setObjectName("bsag_assetType_comboBox")
        self.bsag_assetType_comboBox.addItem("")
        self.bsag_assetType_comboBox.addItem("")
        self.bsag_assetType_comboBox.addItem("")
        self.bsag_assetType_comboBox.addItem("")
        self.bsag_assetType_comboBox.addItem("")
        self.gridLayout.addWidget(self.bsag_assetType_comboBox, 3, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bsag_ep_LE = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsag_ep_LE.sizePolicy().hasHeightForWidth())
        self.bsag_ep_LE.setSizePolicy(sizePolicy)
        self.bsag_ep_LE.setMaximumSize(QtCore.QSize(20, 20))
        self.bsag_ep_LE.setObjectName("bsag_ep_LE")
        self.horizontalLayout.addWidget(self.bsag_ep_LE)
        self.bsag_epNumber_LE = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsag_epNumber_LE.sizePolicy().hasHeightForWidth())
        self.bsag_epNumber_LE.setSizePolicy(sizePolicy)
        self.bsag_epNumber_LE.setMaximumSize(QtCore.QSize(16777215, 20))
        self.bsag_epNumber_LE.setObjectName("bsag_epNumber_LE")
        self.horizontalLayout.addWidget(self.bsag_epNumber_LE)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.bsag_mainLogo_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsag_mainLogo_lbl.sizePolicy().hasHeightForWidth())
        self.bsag_mainLogo_lbl.setSizePolicy(sizePolicy)
        self.bsag_mainLogo_lbl.setMaximumSize(QtCore.QSize(500, 50))
        self.bsag_mainLogo_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bsag_mainLogo_lbl.setObjectName("bsag_mainLogo_lbl")
        self.gridLayout_2.addWidget(self.bsag_mainLogo_lbl, 0, 0, 1, 1)
        bsag_assetGenerate_MW.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(bsag_assetGenerate_MW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        bsag_assetGenerate_MW.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(bsag_assetGenerate_MW)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(bsag_assetGenerate_MW)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), bsag_assetGenerate_MW.close)
        QtCore.QMetaObject.connectSlotsByName(bsag_assetGenerate_MW)

    def retranslateUi(self, bsag_assetGenerate_MW):
        bsag_assetGenerate_MW.setWindowTitle(QtGui.QApplication.translate("bsag_assetGenerate_MW", "BSW Asset Create", None, QtGui.QApplication.UnicodeUTF8))
        self.bsag_createAsset_pb.setText(QtGui.QApplication.translate("bsag_assetGenerate_MW", "Create Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.bsag_assetGrade_comboBox.setItemText(0, QtGui.QApplication.translate("bsag_assetGenerate_MW", "Primary", None, QtGui.QApplication.UnicodeUTF8))
        self.bsag_assetGrade_comboBox.setItemText(1, QtGui.QApplication.translate("bsag_assetGenerate_MW", "Secondary", None, QtGui.QApplication.UnicodeUTF8))
        self.bsag_assetGrade_comboBox.setItemText(2, QtGui.QApplication.translate("bsag_assetGenerate_MW", "Tertiary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("bsag_assetGenerate_MW", "Episode Num:-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("bsag_assetGenerate_MW", "Asset Grade:-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("bsag_assetGenerate_MW", "Asset Type:-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("bsag_assetGenerate_MW", "Asset Name:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bsag_assetName_LE.setPlaceholderText(QtGui.QApplication.translate("bsag_assetGenerate_MW", "dodo (starts with lower case)", None, QtGui.QApplication.UnicodeUTF8))
        self.bsag_assetType_comboBox.setItemText(0, QtGui.QApplication.translate("bsag_assetGenerate_MW", "Character", None, QtGui.QApplication.UnicodeUTF8))
        self.bsag_assetType_comboBox.setItemText(1, QtGui.QApplication.translate("bsag_assetGenerate_MW", "Prop", None, QtGui.QApplication.UnicodeUTF8))
        self.bsag_assetType_comboBox.setItemText(2, QtGui.QApplication.translate("bsag_assetGenerate_MW", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.bsag_assetType_comboBox.setItemText(3, QtGui.QApplication.translate("bsag_assetGenerate_MW", "SetElement", None, QtGui.QApplication.UnicodeUTF8))
        self.bsag_assetType_comboBox.setItemText(4, QtGui.QApplication.translate("bsag_assetGenerate_MW", "Vehicle", None, QtGui.QApplication.UnicodeUTF8))
        self.bsag_ep_LE.setText(QtGui.QApplication.translate("bsag_assetGenerate_MW", "ep", None, QtGui.QApplication.UnicodeUTF8))
        self.bsag_epNumber_LE.setPlaceholderText(QtGui.QApplication.translate("bsag_assetGenerate_MW", "000 (Numbers Only)", None, QtGui.QApplication.UnicodeUTF8))
        self.bsag_mainLogo_lbl.setText(QtGui.QApplication.translate("bsag_assetGenerate_MW", "Create Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("bsag_assetGenerate_MW", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("bsag_assetGenerate_MW", "Exit", None, QtGui.QApplication.UnicodeUTF8))

