# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:/bsw_programation/01_maya/Pipeline/bsPipe/bsPipe/bs_ui/bsui_asset/bsui_assetManager.ui'
#
# Created: Tue Oct 17 13:08:07 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_bs_assetManagerMainWin(object):
    def setupUi(self, bs_assetManagerMainWin):
        bs_assetManagerMainWin.setObjectName("bs_assetManagerMainWin")
        bs_assetManagerMainWin.resize(902, 753)
        self.centralwidget = QtGui.QWidget(bs_assetManagerMainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.logo_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.logo_lbl.sizePolicy().hasHeightForWidth())
        self.logo_lbl.setSizePolicy(sizePolicy)
        self.logo_lbl.setMaximumSize(QtCore.QSize(16777215, 50))
        self.logo_lbl.setText("")
        self.logo_lbl.setObjectName("logo_lbl")
        self.gridLayout_2.addWidget(self.logo_lbl, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.bsAm_category_cBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsAm_category_cBox.sizePolicy().hasHeightForWidth())
        self.bsAm_category_cBox.setSizePolicy(sizePolicy)
        self.bsAm_category_cBox.setMaximumSize(QtCore.QSize(108, 16777215))
        self.bsAm_category_cBox.setObjectName("bsAm_category_cBox")
        self.bsAm_category_cBox.addItem("")
        self.bsAm_category_cBox.addItem("")
        self.bsAm_category_cBox.addItem("")
        self.bsAm_category_cBox.addItem("")
        self.bsAm_category_cBox.addItem("")
        self.horizontalLayout_3.addWidget(self.bsAm_category_cBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bsAm_refresh_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsAm_refresh_pb.sizePolicy().hasHeightForWidth())
        self.bsAm_refresh_pb.setSizePolicy(sizePolicy)
        self.bsAm_refresh_pb.setMinimumSize(QtCore.QSize(0, 40))
        self.bsAm_refresh_pb.setObjectName("bsAm_refresh_pb")
        self.horizontalLayout_3.addWidget(self.bsAm_refresh_pb)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bsAm_open_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsAm_open_pb.sizePolicy().hasHeightForWidth())
        self.bsAm_open_pb.setSizePolicy(sizePolicy)
        self.bsAm_open_pb.setMinimumSize(QtCore.QSize(0, 40))
        self.bsAm_open_pb.setObjectName("bsAm_open_pb")
        self.horizontalLayout_2.addWidget(self.bsAm_open_pb)
        self.bsAm_import_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsAm_import_pb.sizePolicy().hasHeightForWidth())
        self.bsAm_import_pb.setSizePolicy(sizePolicy)
        self.bsAm_import_pb.setMinimumSize(QtCore.QSize(0, 40))
        self.bsAm_import_pb.setObjectName("bsAm_import_pb")
        self.horizontalLayout_2.addWidget(self.bsAm_import_pb)
        self.bsAm_reference_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsAm_reference_pb.sizePolicy().hasHeightForWidth())
        self.bsAm_reference_pb.setSizePolicy(sizePolicy)
        self.bsAm_reference_pb.setMinimumSize(QtCore.QSize(0, 40))
        self.bsAm_reference_pb.setObjectName("bsAm_reference_pb")
        self.horizontalLayout_2.addWidget(self.bsAm_reference_pb)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bsAm_asset_tw = QtGui.QTabWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsAm_asset_tw.sizePolicy().hasHeightForWidth())
        self.bsAm_asset_tw.setSizePolicy(sizePolicy)
        self.bsAm_asset_tw.setMinimumSize(QtCore.QSize(300, 0))
        self.bsAm_asset_tw.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bsAm_asset_tw.setObjectName("bsAm_asset_tw")
        self.chars_tab = QtGui.QWidget()
        self.chars_tab.setObjectName("chars_tab")
        self.bsAm_chars_lw = QtGui.QListWidget(self.chars_tab)
        self.bsAm_chars_lw.setGeometry(QtCore.QRect(0, 40, 311, 491))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bsAm_chars_lw.sizePolicy().hasHeightForWidth())
        self.bsAm_chars_lw.setSizePolicy(sizePolicy)
        self.bsAm_chars_lw.setObjectName("bsAm_chars_lw")
        self.bsAm_charSearch_LE = QtGui.QLineEdit(self.chars_tab)
        self.bsAm_charSearch_LE.setGeometry(QtCore.QRect(0, 10, 311, 21))
        self.bsAm_charSearch_LE.setObjectName("bsAm_charSearch_LE")
        self.bsAm_asset_tw.addTab(self.chars_tab, "")
        self.props_tab = QtGui.QWidget()
        self.props_tab.setObjectName("props_tab")
        self.bsAm_props_lw = QtGui.QListWidget(self.props_tab)
        self.bsAm_props_lw.setGeometry(QtCore.QRect(0, 40, 311, 491))
        self.bsAm_props_lw.setObjectName("bsAm_props_lw")
        self.bsAm_propSearch_LE = QtGui.QLineEdit(self.props_tab)
        self.bsAm_propSearch_LE.setGeometry(QtCore.QRect(0, 10, 311, 21))
        self.bsAm_propSearch_LE.setObjectName("bsAm_propSearch_LE")
        self.bsAm_asset_tw.addTab(self.props_tab, "")
        self.sets_tab = QtGui.QWidget()
        self.sets_tab.setObjectName("sets_tab")
        self.bsAm_sets_lw = QtGui.QListWidget(self.sets_tab)
        self.bsAm_sets_lw.setGeometry(QtCore.QRect(0, 40, 311, 491))
        self.bsAm_sets_lw.setObjectName("bsAm_sets_lw")
        self.bsAm_setSearch_LE = QtGui.QLineEdit(self.sets_tab)
        self.bsAm_setSearch_LE.setGeometry(QtCore.QRect(0, 10, 311, 21))
        self.bsAm_setSearch_LE.setObjectName("bsAm_setSearch_LE")
        self.bsAm_asset_tw.addTab(self.sets_tab, "")
        self.setElements_tab = QtGui.QWidget()
        self.setElements_tab.setObjectName("setElements_tab")
        self.bsAm_setElems_lw = QtGui.QListWidget(self.setElements_tab)
        self.bsAm_setElems_lw.setGeometry(QtCore.QRect(0, 40, 311, 491))
        self.bsAm_setElems_lw.setObjectName("bsAm_setElems_lw")
        self.bsAm_setElementSearch_LE = QtGui.QLineEdit(self.setElements_tab)
        self.bsAm_setElementSearch_LE.setGeometry(QtCore.QRect(0, 10, 311, 21))
        self.bsAm_setElementSearch_LE.setObjectName("bsAm_setElementSearch_LE")
        self.bsAm_asset_tw.addTab(self.setElements_tab, "")
        self.vehicles_tab = QtGui.QWidget()
        self.vehicles_tab.setObjectName("vehicles_tab")
        self.bsAm_vehicles_lw = QtGui.QListWidget(self.vehicles_tab)
        self.bsAm_vehicles_lw.setGeometry(QtCore.QRect(0, 40, 311, 491))
        self.bsAm_vehicles_lw.setObjectName("bsAm_vehicles_lw")
        self.bsAm_vehicleSearch_LE = QtGui.QLineEdit(self.vehicles_tab)
        self.bsAm_vehicleSearch_LE.setGeometry(QtCore.QRect(0, 10, 311, 21))
        self.bsAm_vehicleSearch_LE.setObjectName("bsAm_vehicleSearch_LE")
        self.bsAm_asset_tw.addTab(self.vehicles_tab, "")
        self.verticalLayout.addWidget(self.bsAm_asset_tw)
        self.bsAm_assetVersions_lw = QtGui.QListWidget(self.splitter)
        self.bsAm_assetVersions_lw.setObjectName("bsAm_assetVersions_lw")
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imageView_lbl = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageView_lbl.sizePolicy().hasHeightForWidth())
        self.imageView_lbl.setSizePolicy(sizePolicy)
        self.imageView_lbl.setMaximumSize(QtCore.QSize(16777215, 181))
        self.imageView_lbl.setText("")
        self.imageView_lbl.setObjectName("imageView_lbl")
        self.verticalLayout_2.addWidget(self.imageView_lbl)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.type_lbl = QtGui.QLabel(self.layoutWidget1)
        self.type_lbl.setText("")
        self.type_lbl.setObjectName("type_lbl")
        self.gridLayout.addWidget(self.type_lbl, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.name_lbl = QtGui.QLabel(self.layoutWidget1)
        self.name_lbl.setText("")
        self.name_lbl.setObjectName("name_lbl")
        self.gridLayout.addWidget(self.name_lbl, 0, 1, 1, 1)
        self.version_lbl = QtGui.QLabel(self.layoutWidget1)
        self.version_lbl.setText("")
        self.version_lbl.setObjectName("version_lbl")
        self.gridLayout.addWidget(self.version_lbl, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.bsAm_versionInfo_lw = QtGui.QListWidget(self.layoutWidget1)
        self.bsAm_versionInfo_lw.setObjectName("bsAm_versionInfo_lw")
        self.verticalLayout_2.addWidget(self.bsAm_versionInfo_lw)
        self.gridLayout_2.addWidget(self.splitter, 2, 0, 1, 1)
        bs_assetManagerMainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(bs_assetManagerMainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        bs_assetManagerMainWin.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(bs_assetManagerMainWin)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(bs_assetManagerMainWin)
        self.bsAm_asset_tw.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), bs_assetManagerMainWin.close)
        QtCore.QMetaObject.connectSlotsByName(bs_assetManagerMainWin)

    def retranslateUi(self, bs_assetManagerMainWin):
        bs_assetManagerMainWin.setWindowTitle(QtGui.QApplication.translate("bs_assetManagerMainWin", "Bioscopewala Asset Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.logo_lbl.setStatusTip(QtGui.QApplication.translate("bs_assetManagerMainWin", "ui logo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("bs_assetManagerMainWin", "Category:-", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_category_cBox.setItemText(0, QtGui.QApplication.translate("bs_assetManagerMainWin", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_category_cBox.setItemText(1, QtGui.QApplication.translate("bs_assetManagerMainWin", "Texture", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_category_cBox.setItemText(2, QtGui.QApplication.translate("bs_assetManagerMainWin", "Rig", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_category_cBox.setItemText(3, QtGui.QApplication.translate("bs_assetManagerMainWin", "Light", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_category_cBox.setItemText(4, QtGui.QApplication.translate("bs_assetManagerMainWin", "FX", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_refresh_pb.setText(QtGui.QApplication.translate("bs_assetManagerMainWin", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_open_pb.setText(QtGui.QApplication.translate("bs_assetManagerMainWin", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_import_pb.setText(QtGui.QApplication.translate("bs_assetManagerMainWin", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_reference_pb.setText(QtGui.QApplication.translate("bs_assetManagerMainWin", "Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_asset_tw.setTabText(self.bsAm_asset_tw.indexOf(self.chars_tab), QtGui.QApplication.translate("bs_assetManagerMainWin", "Chars", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_asset_tw.setTabText(self.bsAm_asset_tw.indexOf(self.props_tab), QtGui.QApplication.translate("bs_assetManagerMainWin", "Props", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_asset_tw.setTabText(self.bsAm_asset_tw.indexOf(self.sets_tab), QtGui.QApplication.translate("bs_assetManagerMainWin", "Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_asset_tw.setTabText(self.bsAm_asset_tw.indexOf(self.setElements_tab), QtGui.QApplication.translate("bs_assetManagerMainWin", "SetElement", None, QtGui.QApplication.UnicodeUTF8))
        self.bsAm_asset_tw.setTabText(self.bsAm_asset_tw.indexOf(self.vehicles_tab), QtGui.QApplication.translate("bs_assetManagerMainWin", "Vehicles", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("bs_assetManagerMainWin", "Name:-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("bs_assetManagerMainWin", "Version:-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("bs_assetManagerMainWin", "Type:-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("bs_assetManagerMainWin", "Version Info", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("bs_assetManagerMainWin", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("bs_assetManagerMainWin", "Exit", None, QtGui.QApplication.UnicodeUTF8))

