# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:/bsw_programation/01_maya/Pipeline/bsPipe/bsPipe/bs_ui/bsui_sanity/bsui_sanityMod.ui'
#
# Created: Thu Aug 24 16:41:52 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_bs_san_MainWindow(object):
    def setupUi(self, bs_san_MainWindow):
        bs_san_MainWindow.setObjectName("bs_san_MainWindow")
        bs_san_MainWindow.resize(500, 589)
        self.centralwidget = QtGui.QWidget(bs_san_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bs_san_checkDuplicates_c_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkDuplicates_c_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkDuplicates_c_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkDuplicates_c_pb.setObjectName("bs_san_checkDuplicates_c_pb")
        self.gridLayout.addWidget(self.bs_san_checkDuplicates_c_pb, 0, 1, 1, 1)
        self.bs_san_checkDuplicates_cb = QtGui.QCheckBox(self.centralwidget)
        self.bs_san_checkDuplicates_cb.setObjectName("bs_san_checkDuplicates_cb")
        self.gridLayout.addWidget(self.bs_san_checkDuplicates_cb, 0, 0, 1, 1)
        self.bs_san_checkRenderLayer_c_pb = QtGui.QPushButton(self.centralwidget)
        self.bs_san_checkRenderLayer_c_pb.setObjectName("bs_san_checkRenderLayer_c_pb")
        self.gridLayout.addWidget(self.bs_san_checkRenderLayer_c_pb, 2, 1, 1, 1)
        self.bs_san_checkDisplayLayer_cb = QtGui.QCheckBox(self.centralwidget)
        self.bs_san_checkDisplayLayer_cb.setObjectName("bs_san_checkDisplayLayer_cb")
        self.gridLayout.addWidget(self.bs_san_checkDisplayLayer_cb, 1, 0, 1, 1)
        self.bs_san_checkDisplayLayer_s_pb = QtGui.QPushButton(self.centralwidget)
        self.bs_san_checkDisplayLayer_s_pb.setObjectName("bs_san_checkDisplayLayer_s_pb")
        self.gridLayout.addWidget(self.bs_san_checkDisplayLayer_s_pb, 1, 2, 1, 1)
        self.bs_san_checkDisplayLayer_c_pb = QtGui.QPushButton(self.centralwidget)
        self.bs_san_checkDisplayLayer_c_pb.setObjectName("bs_san_checkDisplayLayer_c_pb")
        self.gridLayout.addWidget(self.bs_san_checkDisplayLayer_c_pb, 1, 1, 1, 1)
        self.bs_san_checkRenderLayer_cb = QtGui.QCheckBox(self.centralwidget)
        self.bs_san_checkRenderLayer_cb.setObjectName("bs_san_checkRenderLayer_cb")
        self.gridLayout.addWidget(self.bs_san_checkRenderLayer_cb, 2, 0, 1, 1)
        self.bs_san_checkRenderLayer_s_pb = QtGui.QPushButton(self.centralwidget)
        self.bs_san_checkRenderLayer_s_pb.setObjectName("bs_san_checkRenderLayer_s_pb")
        self.gridLayout.addWidget(self.bs_san_checkRenderLayer_s_pb, 2, 2, 1, 1)
        self.bs_san_checkDuplicates_s_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkDuplicates_s_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkDuplicates_s_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkDuplicates_s_pb.setObjectName("bs_san_checkDuplicates_s_pb")
        self.gridLayout.addWidget(self.bs_san_checkDuplicates_s_pb, 0, 2, 1, 1)
        self.bs_san_checkNamespaces_cb = QtGui.QCheckBox(self.centralwidget)
        self.bs_san_checkNamespaces_cb.setObjectName("bs_san_checkNamespaces_cb")
        self.gridLayout.addWidget(self.bs_san_checkNamespaces_cb, 3, 0, 1, 1)
        self.bs_san_checkNamespaces_c_pb = QtGui.QPushButton(self.centralwidget)
        self.bs_san_checkNamespaces_c_pb.setObjectName("bs_san_checkNamespaces_c_pb")
        self.gridLayout.addWidget(self.bs_san_checkNamespaces_c_pb, 3, 1, 1, 1)
        self.bs_san_checkNamespaces_s_pb = QtGui.QPushButton(self.centralwidget)
        self.bs_san_checkNamespaces_s_pb.setObjectName("bs_san_checkNamespaces_s_pb")
        self.gridLayout.addWidget(self.bs_san_checkNamespaces_s_pb, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bs_san_checkAllTransFreeze_c_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkAllTransFreeze_c_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkAllTransFreeze_c_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkAllTransFreeze_c_pb.setObjectName("bs_san_checkAllTransFreeze_c_pb")
        self.gridLayout_2.addWidget(self.bs_san_checkAllTransFreeze_c_pb, 0, 1, 1, 1)
        self.bs_san_checkMoreThan1Shapes_s_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkMoreThan1Shapes_s_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkMoreThan1Shapes_s_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkMoreThan1Shapes_s_pb.setObjectName("bs_san_checkMoreThan1Shapes_s_pb")
        self.gridLayout_2.addWidget(self.bs_san_checkMoreThan1Shapes_s_pb, 4, 2, 1, 1)
        self.bs_san_checkAllVertFreeze_cb = QtGui.QCheckBox(self.centralwidget)
        self.bs_san_checkAllVertFreeze_cb.setObjectName("bs_san_checkAllVertFreeze_cb")
        self.gridLayout_2.addWidget(self.bs_san_checkAllVertFreeze_cb, 1, 0, 1, 1)
        self.bs_san_checkGeoBelow0_s_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkGeoBelow0_s_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkGeoBelow0_s_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkGeoBelow0_s_pb.setObjectName("bs_san_checkGeoBelow0_s_pb")
        self.gridLayout_2.addWidget(self.bs_san_checkGeoBelow0_s_pb, 3, 2, 1, 1)
        self.bs_san_checkTopGroupPiv0_cb = QtGui.QCheckBox(self.centralwidget)
        self.bs_san_checkTopGroupPiv0_cb.setObjectName("bs_san_checkTopGroupPiv0_cb")
        self.gridLayout_2.addWidget(self.bs_san_checkTopGroupPiv0_cb, 2, 0, 1, 1)
        self.bs_san_checkMoreThan1Shapes_c_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkMoreThan1Shapes_c_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkMoreThan1Shapes_c_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkMoreThan1Shapes_c_pb.setObjectName("bs_san_checkMoreThan1Shapes_c_pb")
        self.gridLayout_2.addWidget(self.bs_san_checkMoreThan1Shapes_c_pb, 4, 1, 1, 1)
        self.bs_san_checkTopGroupPiv0_c_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkTopGroupPiv0_c_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkTopGroupPiv0_c_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkTopGroupPiv0_c_pb.setObjectName("bs_san_checkTopGroupPiv0_c_pb")
        self.gridLayout_2.addWidget(self.bs_san_checkTopGroupPiv0_c_pb, 2, 1, 1, 1)
        self.bs_san_checkTopGroupPiv0_s_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkTopGroupPiv0_s_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkTopGroupPiv0_s_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkTopGroupPiv0_s_pb.setObjectName("bs_san_checkTopGroupPiv0_s_pb")
        self.gridLayout_2.addWidget(self.bs_san_checkTopGroupPiv0_s_pb, 2, 2, 1, 1)
        self.bs_san_checkAllVertFreeze_c_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkAllVertFreeze_c_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkAllVertFreeze_c_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkAllVertFreeze_c_pb.setObjectName("bs_san_checkAllVertFreeze_c_pb")
        self.gridLayout_2.addWidget(self.bs_san_checkAllVertFreeze_c_pb, 1, 1, 1, 1)
        self.bs_san_checkGeoBelow0_cb = QtGui.QCheckBox(self.centralwidget)
        self.bs_san_checkGeoBelow0_cb.setObjectName("bs_san_checkGeoBelow0_cb")
        self.gridLayout_2.addWidget(self.bs_san_checkGeoBelow0_cb, 3, 0, 1, 1)
        self.bs_san_checkGeoBelow0_c_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkGeoBelow0_c_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkGeoBelow0_c_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkGeoBelow0_c_pb.setObjectName("bs_san_checkGeoBelow0_c_pb")
        self.gridLayout_2.addWidget(self.bs_san_checkGeoBelow0_c_pb, 3, 1, 1, 1)
        self.bs_san_checkAllVertFreeze_s_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkAllVertFreeze_s_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkAllVertFreeze_s_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkAllVertFreeze_s_pb.setObjectName("bs_san_checkAllVertFreeze_s_pb")
        self.gridLayout_2.addWidget(self.bs_san_checkAllVertFreeze_s_pb, 1, 2, 1, 1)
        self.bs_san_checkMoreThan1Shapes_cb = QtGui.QCheckBox(self.centralwidget)
        self.bs_san_checkMoreThan1Shapes_cb.setObjectName("bs_san_checkMoreThan1Shapes_cb")
        self.gridLayout_2.addWidget(self.bs_san_checkMoreThan1Shapes_cb, 4, 0, 1, 1)
        self.bs_san_checkAllTransFreeze_s_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkAllTransFreeze_s_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkAllTransFreeze_s_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkAllTransFreeze_s_pb.setObjectName("bs_san_checkAllTransFreeze_s_pb")
        self.gridLayout_2.addWidget(self.bs_san_checkAllTransFreeze_s_pb, 0, 2, 1, 1)
        self.bs_san_checkAllTransFreeze_cb = QtGui.QCheckBox(self.centralwidget)
        self.bs_san_checkAllTransFreeze_cb.setObjectName("bs_san_checkAllTransFreeze_cb")
        self.gridLayout_2.addWidget(self.bs_san_checkAllTransFreeze_cb, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bs_san_checkAllGeoEndGeo_s_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkAllGeoEndGeo_s_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkAllGeoEndGeo_s_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkAllGeoEndGeo_s_pb.setObjectName("bs_san_checkAllGeoEndGeo_s_pb")
        self.gridLayout_3.addWidget(self.bs_san_checkAllGeoEndGeo_s_pb, 0, 2, 1, 1)
        self.bs_san_checkAllTransStartLowerCase_cb = QtGui.QCheckBox(self.centralwidget)
        self.bs_san_checkAllTransStartLowerCase_cb.setObjectName("bs_san_checkAllTransStartLowerCase_cb")
        self.gridLayout_3.addWidget(self.bs_san_checkAllTransStartLowerCase_cb, 3, 0, 1, 1)
        self.bs_san_checkAllTransStartLowerCase_s_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkAllTransStartLowerCase_s_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkAllTransStartLowerCase_s_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkAllTransStartLowerCase_s_pb.setObjectName("bs_san_checkAllTransStartLowerCase_s_pb")
        self.gridLayout_3.addWidget(self.bs_san_checkAllTransStartLowerCase_s_pb, 3, 2, 1, 1)
        self.bs_san_checkAllGroupEndGrp_cb = QtGui.QCheckBox(self.centralwidget)
        self.bs_san_checkAllGroupEndGrp_cb.setObjectName("bs_san_checkAllGroupEndGrp_cb")
        self.gridLayout_3.addWidget(self.bs_san_checkAllGroupEndGrp_cb, 1, 0, 1, 1)
        self.bs_san_checkShapeName_c_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkShapeName_c_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkShapeName_c_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkShapeName_c_pb.setObjectName("bs_san_checkShapeName_c_pb")
        self.gridLayout_3.addWidget(self.bs_san_checkShapeName_c_pb, 2, 1, 1, 1)
        self.bs_san_checkAllGroupEndGrp_s_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkAllGroupEndGrp_s_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkAllGroupEndGrp_s_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkAllGroupEndGrp_s_pb.setObjectName("bs_san_checkAllGroupEndGrp_s_pb")
        self.gridLayout_3.addWidget(self.bs_san_checkAllGroupEndGrp_s_pb, 1, 2, 1, 1)
        self.bs_san_checkShapeName_cb = QtGui.QCheckBox(self.centralwidget)
        self.bs_san_checkShapeName_cb.setObjectName("bs_san_checkShapeName_cb")
        self.gridLayout_3.addWidget(self.bs_san_checkShapeName_cb, 2, 0, 1, 1)
        self.bs_san_checkAllTransStartLowerCase_c_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkAllTransStartLowerCase_c_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkAllTransStartLowerCase_c_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkAllTransStartLowerCase_c_pb.setObjectName("bs_san_checkAllTransStartLowerCase_c_pb")
        self.gridLayout_3.addWidget(self.bs_san_checkAllTransStartLowerCase_c_pb, 3, 1, 1, 1)
        self.bs_san_checkAllGeoEndGeo_c_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkAllGeoEndGeo_c_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkAllGeoEndGeo_c_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkAllGeoEndGeo_c_pb.setObjectName("bs_san_checkAllGeoEndGeo_c_pb")
        self.gridLayout_3.addWidget(self.bs_san_checkAllGeoEndGeo_c_pb, 0, 1, 1, 1)
        self.bs_san_checkAllGroupEndGrp_c_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkAllGroupEndGrp_c_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkAllGroupEndGrp_c_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkAllGroupEndGrp_c_pb.setObjectName("bs_san_checkAllGroupEndGrp_c_pb")
        self.gridLayout_3.addWidget(self.bs_san_checkAllGroupEndGrp_c_pb, 1, 1, 1, 1)
        self.bs_san_checkShapeName_s_pb = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_checkShapeName_s_pb.sizePolicy().hasHeightForWidth())
        self.bs_san_checkShapeName_s_pb.setSizePolicy(sizePolicy)
        self.bs_san_checkShapeName_s_pb.setObjectName("bs_san_checkShapeName_s_pb")
        self.gridLayout_3.addWidget(self.bs_san_checkShapeName_s_pb, 2, 2, 1, 1)
        self.bs_san_checkAllGeoEndGeo_cb = QtGui.QCheckBox(self.centralwidget)
        self.bs_san_checkAllGeoEndGeo_cb.setObjectName("bs_san_checkAllGeoEndGeo_cb")
        self.gridLayout_3.addWidget(self.bs_san_checkAllGeoEndGeo_cb, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bs_san_selectAllCB_pb = QtGui.QPushButton(self.centralwidget)
        self.bs_san_selectAllCB_pb.setObjectName("bs_san_selectAllCB_pb")
        self.horizontalLayout.addWidget(self.bs_san_selectAllCB_pb)
        self.bs_san_deselectAllCB_pb = QtGui.QPushButton(self.centralwidget)
        self.bs_san_deselectAllCB_pb.setObjectName("bs_san_deselectAllCB_pb")
        self.horizontalLayout.addWidget(self.bs_san_deselectAllCB_pb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.bs_san_sanityCheck_pb = QtGui.QPushButton(self.centralwidget)
        self.bs_san_sanityCheck_pb.setObjectName("bs_san_sanityCheck_pb")
        self.verticalLayout.addWidget(self.bs_san_sanityCheck_pb)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.bs_san_logo_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs_san_logo_lbl.sizePolicy().hasHeightForWidth())
        self.bs_san_logo_lbl.setSizePolicy(sizePolicy)
        self.bs_san_logo_lbl.setMinimumSize(QtCore.QSize(0, 30))
        self.bs_san_logo_lbl.setText("")
        self.bs_san_logo_lbl.setObjectName("bs_san_logo_lbl")
        self.gridLayout_4.addWidget(self.bs_san_logo_lbl, 0, 0, 1, 1)
        bs_san_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(bs_san_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHel = QtGui.QMenu(self.menubar)
        self.menuHel.setObjectName("menuHel")
        bs_san_MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(bs_san_MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(bs_san_MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuHel.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHel.menuAction())

        self.retranslateUi(bs_san_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(bs_san_MainWindow)

    def retranslateUi(self, bs_san_MainWindow):
        bs_san_MainWindow.setWindowTitle(QtGui.QApplication.translate("bs_san_MainWindow", "BSW Sanity Check", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("bs_san_MainWindow", "Basic", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkDuplicates_c_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkDuplicates_cb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "Check Duplicates", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkRenderLayer_c_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkDisplayLayer_cb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "Check Display Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkDisplayLayer_s_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkDisplayLayer_c_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkRenderLayer_cb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "Check Render Layers", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkRenderLayer_s_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkDuplicates_s_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkNamespaces_cb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "Check Namespaces", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkNamespaces_c_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkNamespaces_s_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("bs_san_MainWindow", "Transform Check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllTransFreeze_c_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkMoreThan1Shapes_s_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllVertFreeze_cb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check all vertex is freezed", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkGeoBelow0_s_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkTopGroupPiv0_cb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check top group node pivot to world 0", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkMoreThan1Shapes_c_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkTopGroupPiv0_c_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkTopGroupPiv0_s_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllVertFreeze_c_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkGeoBelow0_cb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check no geo below than world 0", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkGeoBelow0_c_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllVertFreeze_s_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkMoreThan1Shapes_cb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check more than one shape on geo", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllTransFreeze_s_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllTransFreeze_cb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check all transforms is freezed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("bs_san_MainWindow", "Naming Convention", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllGeoEndGeo_s_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllTransStartLowerCase_cb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check all geometry and grouops startswith lower case", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllTransStartLowerCase_s_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllGroupEndGrp_cb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check all group is endswith \"_grp\"", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkShapeName_c_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllGroupEndGrp_s_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkShapeName_cb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check all shape names is correct", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllTransStartLowerCase_c_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllGeoEndGeo_c_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllGroupEndGrp_c_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkShapeName_s_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_checkAllGeoEndGeo_cb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "check all geo is endswith \"_geo\"", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_selectAllCB_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_deselectAllCB_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "Deselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_san_sanityCheck_pb.setText(QtGui.QApplication.translate("bs_san_MainWindow", "Sanity Check", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("bs_san_MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHel.setTitle(QtGui.QApplication.translate("bs_san_MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("bs_san_MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("bs_san_MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

